In [1]:
import pandas as pd
df = pd.read_csv('data/bookclub_events.csv', 
                 parse_dates=['event_time', 'receipt_time'], 
                 dtype={'learner_id':int, 'contents_code': str, 'library_source' : str, 'media_fm' : str}).drop_duplicates(['row_id'])

In [2]:
df.shape

(23644461, 12)

In [3]:
df['event_name'].value_counts()

video_close         5401530
video_open          4163369
book_open           4041209
book_close          4004269
book_first_open     2246628
video_first_open    1483675
book_complete       1438758
audio_open           421802
audio_close          407875
audio_first_open      35346
Name: event_name, dtype: int64

In [28]:
book_code_null = df[df['book_code'].isnull()]
content_code_null = book_code_null[book_code_null['contents_code'].isnull()]
len(book_code_null), len(content_code_null)

(10136500, 0)

In [12]:
equal_book_contents = df[(df['book_code'].notnull()) & (df['contents_code'].notnull())]
book_ids = equal_book_contents['book_code'].str.extract('BO-(\d+)', expand=False)
content_ids = equal_book_contents['contents_code'].str.extract('CT-(\d+)', expand=False)
print(book_ids, content_ids)

865032      20160329135654842
865033      20140726015827440
865040      20140726015056775
865041      20140726014903467
865044      20140726014730319
865045      20170526154709672
865047      20160329135654842
865048      20150417014719989
865049      20170724102316502
865050      20150417050400895
865056      20170526154709682
865058      20161226152837329
865061      20140726014850379
865065      20150417030605438
865066      20150417014720171
865070      20161226152837329
865073      20140726015905711
865074      20140726013728499
865075      20140726014903467
865076      20160817134916893
865081      20170124180543504
865083      20170124180543504
865084      20140726015827440
865085      20150417044756830
865087      20140726020139839
865089      20140726015521623
865090      20170724102316502
865091      20140726020215086
865095      20170526154709672
865097      20150417050401158
                  ...
23644414    20160621113027843
23644415    20150420190236662
23644417    20150420190236662
23644421    20141030210040223
23644427    20150420190236662
23644437    20161026171156547
23644440    20160803085630682
23644448    20141030210048834
23644451    20170821132107257
23644460    20150420190236662
23644474    20170724102316479
23644475    20170911134228336
23644476    20170821132107285
23644481    20170821132107285
23644484    20141030210042245
23644505    20170821132107257
23644506    20170821132107285
23644517    20170825093227112
23644518    20170821132107257
23644519    20141215134042810
23644535    20170821132107208
23644539    20170821132107257
23644550    20170821132107285
23644558    20170825093227112
23644580    20170821132107208
23644583    20150420190236662
23644594    20170821132107257
23644602    20170821132107208
23644604    20170821132107208
23644615    20161026171155557
Name: book_code, Length: 5973662, dtype: object 865032      20160329135654842
865033      20140726015827440
865040      20140726015056775
865041      20140726014903467
865044      20140726014730319
865045      20170526154709672
865047      20160329135654842
865048      20150417014719989
865049      20170724102316502
865050      20150417050400895
865056      20170526154709682
865058      20161226152837329
865061      20140726014850379
865065      20150417030605438
865066      20150417014720171
865070      20161226152837329
865073      20140726015905711
865074      20140726013728499
865075      20140726014903467
865076      20160817134916893
865081      20170124180543504
865083      20170124180543504
865084      20140726015827440
865085      20150417044756830
865087      20140726020139839
865089      20140726015521623
865090      20170724102316502
865091      20140726020215086
865095      20170526154709672
865097      20150417050401158
                  ...
23644414    20160621113027843
23644415    20150420190236662
23644417    20150420190236662
23644421    20141030210040223
23644427    20150420190236662
23644437    20161026171156548
23644440    20160803085630683
23644448    20141030210048834
23644451    20170821132107257
23644460    20150420190236662
23644474    20170724102316479
23644475    20170911134228336
23644476    20170821132107285
23644481    20170821132107285
23644484    20141030210042245
23644505    20170821132107257
23644506    20170821132107285
23644517    20170825093227112
23644518    20170821132107257
23644519    20141215134042810
23644535    20170821132107208
23644539    20170821132107257
23644550    20170821132107285
23644558    20170825093227112
23644580    20170821132107208
23644583    20150420190236662
23644594    20170821132107257
23644602    20170821132107208
23644604    20170821132107208
23644615    20161026171155557
Name: contents_code, Length: 5973662, dtype: object

In [18]:
# book_ids.equals(content_ids)

# from pandas.util.testing import assert_series_equal
# assert_series_equal(book_ids, content_ids)

s = (book_ids != content_ids)
s[s == True]

865104      True
865200      True
865288      True
865289      True
865313      True
865462      True
865757      True
865762      True
866003      True
866096      True
866498      True
866572      True
866690      True
866775      True
866821      True
866918      True
866940      True
866945      True
866947      True
866978      True
867040      True
867223      True
867344      True
867402      True
867515      True
867633      True
867642      True
867770      True
867837      True
867906      True
            ...
23635701    True
23635765    True
23636946    True
23637016    True
23637192    True
23637197    True
23637909    True
23638724    True
23639057    True
23639561    True
23639624    True
23639808    True
23639857    True
23640180    True
23640227    True
23640384    True
23640539    True
23641146    True
23641580    True
23641869    True
23642030    True
23642232    True
23642255    True
23642314    True
23642780    True
23642992    True
23644097    True
23644164    True
23644437    True
23644440    True
Length: 197254, dtype: bool

In [22]:
book_ids[865104], content_ids[865104]

('20140726014851385', '20140726014851386')

In [26]:
equal_book_contents[equal_book_contents['book_code'] == 'BO-20140726014851385']

,Unnamed: 0,row_id,trial_time,event_name,event_time,receipt_time,learner_id,session_id,book_code,contents_code,library_source,media_fm
865104,865105,000000000006B4FF00000000000539A10000015EA430A8...,1970-01-01,book_close,2017-09-21 11:26:46,2017-09-21 11:35:30,342433,002662316520170921200637,BO-20140726014851385,CT-20140726014851386,NaN,NaN
865757,865758,00000000000757B7000000000006173B0000015EA430A1...,1970-01-01,book_close,2017-09-21 11:26:44,2017-09-21 11:35:16,399163,002680211520170921192617,BO-20140726014851385,CT-20140726014851386,NaN,NaN
866096,866097,000000000000D15E00000000000381D70000015EA43066...,1970-01-01,book_close,2017-09-21 11:26:29,2017-09-21 11:35:27,229847,002618306720170921191259,BO-20140726014851385,CT-20140726014851386,NaN,NaN
866498,866499,0000000000008C6F000000000001757C0000015E9EEF75...,1970-01-01,book_close,2017-09-20 10:57:27,2017-09-20 11:05:48,95612,002470092920170920194142,BO-20140726014851385,CT-20140726014851386,NaN,NaN
868928,868929,000000000007E33E00000000000A063E0000015EA74B9C...,1970-01-01,book_close,2017-09-22 01:55:04,2017-09-22 09:39:58,656958,002737451820170922183022,BO-20140726014851385,CT-20140726014851386,NaN,NaN
870922,870923,000000000007D3DB000000000009F22E0000015EA8F021...,1970-01-01,book_close,2017-09-22 09:34:23,2017-09-22 09:40:55,651822,002736149020170922182219,BO-20140726014851385,CT-20140726014851386,NaN,NaN
871001,871002,000000000007D3DB000000000009F22E0000015EA8EF42...,1970-01-01,book_close,2017-09-22 09:33:26,2017-09-22 09:40:38,651822,002736149020170922182219,BO-20140726014851385,CT-20140726014851386,NaN,NaN
874768,874769,0000000000025C2C000000000008F7470000015EA434E6...,1970-01-01,book_close,2017-09-21 11:31:24,2017-09-21 11:40:29,587591,002726702720170921202230,BO-20140726014851385,CT-20140726014851386,NaN,NaN
877032,877033,0000000000037344000000000002B39F0000015EA8F3C6...,1970-01-01,book_close,2017-09-22 09:38:22,2017-09-22 09:45:47,177055,002572415020170922175459,BO-20140726014851385,CT-20140726014851386,NaN,NaN
877773,877774,000000000007CEA5000000000009EBFD0000015EA84068...,1970-01-01,book_close,2017-09-22 06:22:27,2017-09-22 09:46:08,650237,002735561520170922183909,BO-20140726014851385,CT-20140726014851386,NaN,NaN
878394,878395,000000000005CFF5000000000006F3000000015EA20BFC...,1970-01-01,book_close,2017-09-21 01:27:28,2017-09-21 01:40:05,455424,002698790420170921103351,BO-20140726014851385,CT-20140726014851386,NaN,NaN
878652,878653,000000000003A281000000000002E0F90000015E9EF35D...,1970-01-01,book_close,2017-09-20 11:01:43,2017-09-20 11:10:42,188665,002584891020170920192758,BO-20140726014851385,CT-20140726014851386,NaN,NaN
878685,878686,00000000000010180000000000081F5B0000015E943EFA...,1970-01-01,book_close,2017-09-18 09:08:29,2017-09-19 11:16:44,532315,002724575220170919200839,BO-20140726014851385,CT-20140726014851386,NaN,NaN
879227,879228,0000000000041D7F000000000005D8850000015EA8FA1F...,1970-01-01,book_close,2017-09-22 09:45:18,2017-09-22 09:54:54,383109,002674234320170922175624,BO-20140726014851385,CT-20140726014851386,NaN,NaN
879962,879963,0000000000074442000000000007F2940000015E9EF3DA...,1970-01-01,book_close,2017-09-20 11:02:15,2017-09-20 11:10:50,520852,002721258820170920200157,BO-20140726014851385,CT-20140726014851386,NaN,NaN
880339,880340,0000000000074442000000000007F2940000015E9EF3C3...,1970-01-01,book_close,2017-09-20 11:02:09,2017-09-20 11:10:50,520852,002721258820170920200157,BO-20140726014851385,CT-20140726014851386,NaN,NaN
884050,884051,0000000000074FDD000000000003694A0000015E99D35A...,1970-01-01,book_close,2017-09-19 11:08:39,2017-09-19 11:16:54,223562,002617654920170919194114,BO-20140726014851385,CT-20140726014851386,NaN,NaN
884369,884370,000000000005C3110000000000070DEB0000015E87C63E...,1970-01-01,book_close,2017-09-15 23:01:10,2017-09-15 23:12:52,462315,002699648320170916075602,BO-20140726014851385,CT-20140726014851386,NaN,NaN
885284,885285,0000000000072854000000000007D0890000015EA43CB2...,1970-01-01,book_close,2017-09-21 11:39:55,2017-09-21 11:46:46,512137,002717563420170921203156,BO-20140726014851385,CT-20140726014851386,NaN,NaN
885799,885800,0000000000073676000000000007BBAE0000015EA43C9F...,1970-01-01,book_close,2017-09-21 11:39:50,2017-09-21 11:46:54,506798,002716238720170921202450,BO-20140726014851385,CT-20140726014851386,NaN,NaN
886903,886904,000000000003D3BC0000000000036C010000015EA23467...,1970-01-01,book_close,2017-09-21 02:11:37,2017-09-21 02:19:50,224257,002617033320170921111011,BO-20140726014851385,CT-20140726014851386,NaN,NaN
889517,889518,000000000002E267000000000004DE520000015E99D362...,1970-01-01,book_close,2017-09-19 11:08:41,2017-09-19 11:16:53,319058,002653734520170919180430,BO-20140726014851385,CT-20140726014851386,NaN,NaN
889569,889570,00000000000770CE000000000008C1D10000015E8598F2...,1970-01-01,book_close,2017-09-15 12:52:27,2017-09-15 13:03:22,573905,002727187820170915214307,BO-20140726014851385,CT-20140726014851386,NaN,NaN
889926,889927,0000000000058969000000000006B9FC0000015E9EF580...,1970-01-01,book_close,2017-09-20 11:04:03,2017-09-20 11:11:49,440828,002693095420170920195410,BO-20140726014851385,CT-20140726014851386,NaN,NaN
890018,890019,0000000000062813000000000006B5F20000015EA8FF8A...,1970-01-01,book_close,2017-09-22 09:51:13,2017-09-22 10:00:10,439794,002693022420170922182647,BO-20140726014851385,CT-20140726014851386,NaN,NaN
890492,890493,0000000000069C120000000000078C090000015E9EF5EA...,1970-01-01,book_close,2017-09-20 11:04:30,2017-09-20 11:11:59,494601,002711659620170920195545,BO-20140726014851385,CT-20140726014851386,NaN,NaN
890680,890681,0000000000058E54000000000006C1910000015EA43DD0...,1970-01-01,book_close,2017-09-21 11:41:08,2017-09-21 11:50:09,442769,002694643920170921200215,BO-20140726014851385,CT-20140726014851386,NaN,NaN
891558,891559,000000000000FFA1000000000003A2930000015E9EF6AD...,1970-01-01,book_close,2017-09-20 11:05:20,2017-09-20 11:14:52,238227,002622051020170920190709,BO-20140726014851385,CT-20140726014851386,NaN,NaN
893088,893089,00000000000750720000000000080CB90000015EA90543...,1970-01-01,book_close,2017-09-22 09:57:28,2017-09-22 10:05:33,527545,002725134020170922180327,BO-20140726014851385,CT-20140726014851386,NaN,NaN
894715,894716,000000000007B893000000000009CF030000015E99D4DD...,1970-01-01,book_close,2017-09-19 11:10:18,2017-09-19 11:19:53,642819,002644104520170919200937,BO-20140726014851385,CT-20140726014851386,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12564293,12564294,000000000007C6F5000000000009E17F0000015EBE8B2E...,1970-01-01,book_open,2017-09-26 14:15:46,2017-09-26 14:21:25,647551,002734702720170926231520,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12564809,12564810,000000000001AE980000000000032E660000015EBDD832...,1970-01-01,book_open,2017-09-26 11:00:16,2017-09-26 11:07:47,208486,002602224920170926195050,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12565863,12565864,00000000000404CA000000000008EA7B0000015EBDE11B...,1970-01-01,book_open,2017-09-26 11:10:00,2017-09-26 11:13:31,584315,C10007300420170926194300,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12570217,12570218,00000000000497E300000000000634750000015EBDF265...,1970-01-01,book_open,2017-09-26 11:28:53,2017-09-26 11:33:07,406645,002682024220170926195125,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12571644,12571645,000000000007796F00000000000636DD0000015EBDFA73...,1970-01-01,book_open,2017-09-26 11:37:41,2017-09-26 11:42:52,407261,002682388120170926203446,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12571791,12571792,000000000007644300000000000817CE0000015EBDFB5A...,1970-01-01,book_open,2017-09-26 11:38:40,2017-09-26 11:43:14,530382,002726003020170926203517,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12572267,12572268,0000000000075620000000000007F4730000015EBDFE30...,1970-01-01,book_open,2017-09-26 11:41:46,2017-09-26 11:47:04,521331,002720932820170926203025,BO-20140726014851385,CT-20140726014851386,LD,PDFA
12572937,12572938,000000000007714A000000000008CE990000015EBBA75F...,1970-01-01,book_open,2017-09-26 00:47:42,2017-09-26 11:51:33,577177,002727658920170926204502,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12573179,12573180,000000000003E4AF000000000003036C0000015EBE0387...,1970-01-01,book_open,2017-09-26 11:47:36,2017-09-26 11:52:30,197484,002592481620170926204620,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12574433,12574434,000000000007E3E400000000000A066B0000015EBE0A2E...,1970-01-01,book_open,2017-09-26 11:54:52,2017-09-26 11:58:52,657003,002737400120170926134000,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12574924,12574925,0000000000049E8000000000000623BD0000015EBE0D38...,1970-01-01,book_open,2017-09-26 11:58:11,2017-09-26 12:02:48,402365,002681379520170926204622,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12576816,12576817,000000000002578C00000000000492880000015EA6B525...,1970-01-01,book_open,2017-09-21 23:10:43,2017-09-21 23:20:01,299656,002649154420170922074021,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12577281,12577282,000000000007EA6D00000000000A108D0000015EBE1379...,1970-01-01,book_open,2017-09-26 12:05:01,2017-09-26 12:08:45,659597,002737970520170926210009,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12577950,12577951,000000000006E7A7000000000007ADB50000015E87D93A...,1970-01-01,book_open,2017-09-15 23:21:54,2017-09-15 23:33:05,503221,002715091420170916080315,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12579733,12579734,000000000006BFEA000000000002C8C00000015EBB2CC4...,1970-01-01,book_open,2017-09-25 22:33:47,2017-09-25 22:36:52,182464,002580458520170926073249,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12579779,12579780,000000000006407F00000000000762750000015EBC3008...,1970-01-01,book_open,2017-09-26 03:16:58,2017-09-26 03:21:27,483957,002707244420170926115951,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12581229,12581230,0000000000005F570000000000033F070000015EBE1B1A...,1970-01-01,book_open,2017-09-26 12:13:21,2017-09-26 12:17:46,212743,002605143220170925194745,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12582083,12582084,000000000003575F00000000000574570000015EBDE52E...,1970-01-01,book_open,2017-09-26 11:14:27,2017-09-26 12:23:39,357463,002666784720170926211950,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12582647,12582648,00000000000208A90000000000032B880000015EBE2475...,1970-01-01,book_open,2017-09-26 12:23:34,2017-09-26 12:27:55,207752,002603061420170926212225,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12583567,12583568,0000000000070891000000000007E03F0000015EBE2AA3...,1970-01-01,book_open,2017-09-26 12:30:19,2017-09-26 12:36:23,516159,002720063320170926211312,BO-20140726014851385,CT-20140726014851386,TKI_10,PDFA
12585716,12585717,00000000000432F1000000000005F05D0000015EBE3B83...,1970-01-01,book_open,2017-09-26 12:48:45,2017-09-26 12:52:31,389213,002676773520170926214156,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12586296,12586297,0000000000032314000000000004D41D0000015EBE3FD5...,1970-01-01,book_open,2017-09-26 12:53:28,2017-09-26 12:57:18,316445,002653844020170926213102,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12586893,12586894,000000000001F60D00000000000240930000015EBE4501...,1970-01-01,book_open,2017-09-26 12:59:07,2017-09-26 13:02:43,147603,002543149720170926215331,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12587650,12587651,000000000007AD4F000000000009C64F0000015EBE4E48...,1970-01-01,book_open,2017-09-26 13:09:15,2017-09-26 13:12:21,640591,002730784220170926220538,BO-20140726014851385,CT-20140726014851386,TKI_10,PDFA
12589024,12589025,000000000006B4910000000000077B870000015EBE5D9E...,1970-01-01,book_open,2017-09-26 13:26:00,2017-09-26 13:31:39,490375,002710512120170926221514,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12589058,12589059,0000000000032B0E00000000000563BD0000015EBE5E69...,1970-01-01,book_open,2017-09-26 13:26:52,2017-09-26 13:31:47,353213,002665091220170926210434,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12590588,12590589,000000000000EAEA00000000000241900000015EBE7C74...,1970-01-01,book_open,2017-09-26 13:59:41,2017-09-26 14:01:51,147856,002543322520170926221211,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12593075,12593076,000000000007E0CC00000000000A0AD80000015EA6B3E1...,1970-01-01,book_open,2017-09-21 23:09:20,2017-09-21 23:15:44,658136,002737817320170922080256,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12595379,12595380,0000000000070F04000000000007BE890000015EB7998C...,1970-01-01,book_open,2017-09-25 05:54:07,2017-09-25 05:56:29,507529,002715902220170925145404,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12595493,12595494,000000000004D80B00000000000644DD0000015EB88E9E...,1970-01-01,book_open,2017-09-25 10:21:48,2017-09-25 10:27:06,410845,002684142520170925185012,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA

In [27]:
df[df['book_code'] == 'BO-20140726014851385']

,Unnamed: 0,row_id,trial_time,event_name,event_time,receipt_time,learner_id,session_id,book_code,contents_code,library_source,media_fm
865104,865105,000000000006B4FF00000000000539A10000015EA430A8...,1970-01-01,book_close,2017-09-21 11:26:46,2017-09-21 11:35:30,342433,002662316520170921200637,BO-20140726014851385,CT-20140726014851386,NaN,NaN
865757,865758,00000000000757B7000000000006173B0000015EA430A1...,1970-01-01,book_close,2017-09-21 11:26:44,2017-09-21 11:35:16,399163,002680211520170921192617,BO-20140726014851385,CT-20140726014851386,NaN,NaN
866096,866097,000000000000D15E00000000000381D70000015EA43066...,1970-01-01,book_close,2017-09-21 11:26:29,2017-09-21 11:35:27,229847,002618306720170921191259,BO-20140726014851385,CT-20140726014851386,NaN,NaN
866498,866499,0000000000008C6F000000000001757C0000015E9EEF75...,1970-01-01,book_close,2017-09-20 10:57:27,2017-09-20 11:05:48,95612,002470092920170920194142,BO-20140726014851385,CT-20140726014851386,NaN,NaN
868928,868929,000000000007E33E00000000000A063E0000015EA74B9C...,1970-01-01,book_close,2017-09-22 01:55:04,2017-09-22 09:39:58,656958,002737451820170922183022,BO-20140726014851385,CT-20140726014851386,NaN,NaN
870922,870923,000000000007D3DB000000000009F22E0000015EA8F021...,1970-01-01,book_close,2017-09-22 09:34:23,2017-09-22 09:40:55,651822,002736149020170922182219,BO-20140726014851385,CT-20140726014851386,NaN,NaN
871001,871002,000000000007D3DB000000000009F22E0000015EA8EF42...,1970-01-01,book_close,2017-09-22 09:33:26,2017-09-22 09:40:38,651822,002736149020170922182219,BO-20140726014851385,CT-20140726014851386,NaN,NaN
874768,874769,0000000000025C2C000000000008F7470000015EA434E6...,1970-01-01,book_close,2017-09-21 11:31:24,2017-09-21 11:40:29,587591,002726702720170921202230,BO-20140726014851385,CT-20140726014851386,NaN,NaN
877032,877033,0000000000037344000000000002B39F0000015EA8F3C6...,1970-01-01,book_close,2017-09-22 09:38:22,2017-09-22 09:45:47,177055,002572415020170922175459,BO-20140726014851385,CT-20140726014851386,NaN,NaN
877773,877774,000000000007CEA5000000000009EBFD0000015EA84068...,1970-01-01,book_close,2017-09-22 06:22:27,2017-09-22 09:46:08,650237,002735561520170922183909,BO-20140726014851385,CT-20140726014851386,NaN,NaN
878394,878395,000000000005CFF5000000000006F3000000015EA20BFC...,1970-01-01,book_close,2017-09-21 01:27:28,2017-09-21 01:40:05,455424,002698790420170921103351,BO-20140726014851385,CT-20140726014851386,NaN,NaN
878652,878653,000000000003A281000000000002E0F90000015E9EF35D...,1970-01-01,book_close,2017-09-20 11:01:43,2017-09-20 11:10:42,188665,002584891020170920192758,BO-20140726014851385,CT-20140726014851386,NaN,NaN
878685,878686,00000000000010180000000000081F5B0000015E943EFA...,1970-01-01,book_close,2017-09-18 09:08:29,2017-09-19 11:16:44,532315,002724575220170919200839,BO-20140726014851385,CT-20140726014851386,NaN,NaN
879227,879228,0000000000041D7F000000000005D8850000015EA8FA1F...,1970-01-01,book_close,2017-09-22 09:45:18,2017-09-22 09:54:54,383109,002674234320170922175624,BO-20140726014851385,CT-20140726014851386,NaN,NaN
879962,879963,0000000000074442000000000007F2940000015E9EF3DA...,1970-01-01,book_close,2017-09-20 11:02:15,2017-09-20 11:10:50,520852,002721258820170920200157,BO-20140726014851385,CT-20140726014851386,NaN,NaN
880339,880340,0000000000074442000000000007F2940000015E9EF3C3...,1970-01-01,book_close,2017-09-20 11:02:09,2017-09-20 11:10:50,520852,002721258820170920200157,BO-20140726014851385,CT-20140726014851386,NaN,NaN
884050,884051,0000000000074FDD000000000003694A0000015E99D35A...,1970-01-01,book_close,2017-09-19 11:08:39,2017-09-19 11:16:54,223562,002617654920170919194114,BO-20140726014851385,CT-20140726014851386,NaN,NaN
884369,884370,000000000005C3110000000000070DEB0000015E87C63E...,1970-01-01,book_close,2017-09-15 23:01:10,2017-09-15 23:12:52,462315,002699648320170916075602,BO-20140726014851385,CT-20140726014851386,NaN,NaN
885284,885285,0000000000072854000000000007D0890000015EA43CB2...,1970-01-01,book_close,2017-09-21 11:39:55,2017-09-21 11:46:46,512137,002717563420170921203156,BO-20140726014851385,CT-20140726014851386,NaN,NaN
885799,885800,0000000000073676000000000007BBAE0000015EA43C9F...,1970-01-01,book_close,2017-09-21 11:39:50,2017-09-21 11:46:54,506798,002716238720170921202450,BO-20140726014851385,CT-20140726014851386,NaN,NaN
886903,886904,000000000003D3BC0000000000036C010000015EA23467...,1970-01-01,book_close,2017-09-21 02:11:37,2017-09-21 02:19:50,224257,002617033320170921111011,BO-20140726014851385,CT-20140726014851386,NaN,NaN
889517,889518,000000000002E267000000000004DE520000015E99D362...,1970-01-01,book_close,2017-09-19 11:08:41,2017-09-19 11:16:53,319058,002653734520170919180430,BO-20140726014851385,CT-20140726014851386,NaN,NaN
889569,889570,00000000000770CE000000000008C1D10000015E8598F2...,1970-01-01,book_close,2017-09-15 12:52:27,2017-09-15 13:03:22,573905,002727187820170915214307,BO-20140726014851385,CT-20140726014851386,NaN,NaN
889926,889927,0000000000058969000000000006B9FC0000015E9EF580...,1970-01-01,book_close,2017-09-20 11:04:03,2017-09-20 11:11:49,440828,002693095420170920195410,BO-20140726014851385,CT-20140726014851386,NaN,NaN
890018,890019,0000000000062813000000000006B5F20000015EA8FF8A...,1970-01-01,book_close,2017-09-22 09:51:13,2017-09-22 10:00:10,439794,002693022420170922182647,BO-20140726014851385,CT-20140726014851386,NaN,NaN
890492,890493,0000000000069C120000000000078C090000015E9EF5EA...,1970-01-01,book_close,2017-09-20 11:04:30,2017-09-20 11:11:59,494601,002711659620170920195545,BO-20140726014851385,CT-20140726014851386,NaN,NaN
890680,890681,0000000000058E54000000000006C1910000015EA43DD0...,1970-01-01,book_close,2017-09-21 11:41:08,2017-09-21 11:50:09,442769,002694643920170921200215,BO-20140726014851385,CT-20140726014851386,NaN,NaN
891558,891559,000000000000FFA1000000000003A2930000015E9EF6AD...,1970-01-01,book_close,2017-09-20 11:05:20,2017-09-20 11:14:52,238227,002622051020170920190709,BO-20140726014851385,CT-20140726014851386,NaN,NaN
893088,893089,00000000000750720000000000080CB90000015EA90543...,1970-01-01,book_close,2017-09-22 09:57:28,2017-09-22 10:05:33,527545,002725134020170922180327,BO-20140726014851385,CT-20140726014851386,NaN,NaN
894715,894716,000000000007B893000000000009CF030000015E99D4DD...,1970-01-01,book_close,2017-09-19 11:10:18,2017-09-19 11:19:53,642819,002644104520170919200937,BO-20140726014851385,CT-20140726014851386,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12564293,12564294,000000000007C6F5000000000009E17F0000015EBE8B2E...,1970-01-01,book_open,2017-09-26 14:15:46,2017-09-26 14:21:25,647551,002734702720170926231520,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12564809,12564810,000000000001AE980000000000032E660000015EBDD832...,1970-01-01,book_open,2017-09-26 11:00:16,2017-09-26 11:07:47,208486,002602224920170926195050,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12565863,12565864,00000000000404CA000000000008EA7B0000015EBDE11B...,1970-01-01,book_open,2017-09-26 11:10:00,2017-09-26 11:13:31,584315,C10007300420170926194300,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12570217,12570218,00000000000497E300000000000634750000015EBDF265...,1970-01-01,book_open,2017-09-26 11:28:53,2017-09-26 11:33:07,406645,002682024220170926195125,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12571644,12571645,000000000007796F00000000000636DD0000015EBDFA73...,1970-01-01,book_open,2017-09-26 11:37:41,2017-09-26 11:42:52,407261,002682388120170926203446,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12571791,12571792,000000000007644300000000000817CE0000015EBDFB5A...,1970-01-01,book_open,2017-09-26 11:38:40,2017-09-26 11:43:14,530382,002726003020170926203517,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12572267,12572268,0000000000075620000000000007F4730000015EBDFE30...,1970-01-01,book_open,2017-09-26 11:41:46,2017-09-26 11:47:04,521331,002720932820170926203025,BO-20140726014851385,CT-20140726014851386,LD,PDFA
12572937,12572938,000000000007714A000000000008CE990000015EBBA75F...,1970-01-01,book_open,2017-09-26 00:47:42,2017-09-26 11:51:33,577177,002727658920170926204502,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12573179,12573180,000000000003E4AF000000000003036C0000015EBE0387...,1970-01-01,book_open,2017-09-26 11:47:36,2017-09-26 11:52:30,197484,002592481620170926204620,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12574433,12574434,000000000007E3E400000000000A066B0000015EBE0A2E...,1970-01-01,book_open,2017-09-26 11:54:52,2017-09-26 11:58:52,657003,002737400120170926134000,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12574924,12574925,0000000000049E8000000000000623BD0000015EBE0D38...,1970-01-01,book_open,2017-09-26 11:58:11,2017-09-26 12:02:48,402365,002681379520170926204622,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12576816,12576817,000000000002578C00000000000492880000015EA6B525...,1970-01-01,book_open,2017-09-21 23:10:43,2017-09-21 23:20:01,299656,002649154420170922074021,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12577281,12577282,000000000007EA6D00000000000A108D0000015EBE1379...,1970-01-01,book_open,2017-09-26 12:05:01,2017-09-26 12:08:45,659597,002737970520170926210009,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12577950,12577951,000000000006E7A7000000000007ADB50000015E87D93A...,1970-01-01,book_open,2017-09-15 23:21:54,2017-09-15 23:33:05,503221,002715091420170916080315,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12579733,12579734,000000000006BFEA000000000002C8C00000015EBB2CC4...,1970-01-01,book_open,2017-09-25 22:33:47,2017-09-25 22:36:52,182464,002580458520170926073249,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12579779,12579780,000000000006407F00000000000762750000015EBC3008...,1970-01-01,book_open,2017-09-26 03:16:58,2017-09-26 03:21:27,483957,002707244420170926115951,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12581229,12581230,0000000000005F570000000000033F070000015EBE1B1A...,1970-01-01,book_open,2017-09-26 12:13:21,2017-09-26 12:17:46,212743,002605143220170925194745,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12582083,12582084,000000000003575F00000000000574570000015EBDE52E...,1970-01-01,book_open,2017-09-26 11:14:27,2017-09-26 12:23:39,357463,002666784720170926211950,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12582647,12582648,00000000000208A90000000000032B880000015EBE2475...,1970-01-01,book_open,2017-09-26 12:23:34,2017-09-26 12:27:55,207752,002603061420170926212225,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12583567,12583568,0000000000070891000000000007E03F0000015EBE2AA3...,1970-01-01,book_open,2017-09-26 12:30:19,2017-09-26 12:36:23,516159,002720063320170926211312,BO-20140726014851385,CT-20140726014851386,TKI_10,PDFA
12585716,12585717,00000000000432F1000000000005F05D0000015EBE3B83...,1970-01-01,book_open,2017-09-26 12:48:45,2017-09-26 12:52:31,389213,002676773520170926214156,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12586296,12586297,0000000000032314000000000004D41D0000015EBE3FD5...,1970-01-01,book_open,2017-09-26 12:53:28,2017-09-26 12:57:18,316445,002653844020170926213102,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12586893,12586894,000000000001F60D00000000000240930000015EBE4501...,1970-01-01,book_open,2017-09-26 12:59:07,2017-09-26 13:02:43,147603,002543149720170926215331,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12587650,12587651,000000000007AD4F000000000009C64F0000015EBE4E48...,1970-01-01,book_open,2017-09-26 13:09:15,2017-09-26 13:12:21,640591,002730784220170926220538,BO-20140726014851385,CT-20140726014851386,TKI_10,PDFA
12589024,12589025,000000000006B4910000000000077B870000015EBE5D9E...,1970-01-01,book_open,2017-09-26 13:26:00,2017-09-26 13:31:39,490375,002710512120170926221514,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12589058,12589059,0000000000032B0E00000000000563BD0000015EBE5E69...,1970-01-01,book_open,2017-09-26 13:26:52,2017-09-26 13:31:47,353213,002665091220170926210434,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12590588,12590589,000000000000EAEA00000000000241900000015EBE7C74...,1970-01-01,book_open,2017-09-26 13:59:41,2017-09-26 14:01:51,147856,002543322520170926221211,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12593075,12593076,000000000007E0CC00000000000A0AD80000015EA6B3E1...,1970-01-01,book_open,2017-09-21 23:09:20,2017-09-21 23:15:44,658136,002737817320170922080256,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12595379,12595380,0000000000070F04000000000007BE890000015EB7998C...,1970-01-01,book_open,2017-09-25 05:54:07,2017-09-25 05:56:29,507529,002715902220170925145404,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA
12595493,12595494,000000000004D80B00000000000644DD0000015EB88E9E...,1970-01-01,book_open,2017-09-25 10:21:48,2017-09-25 10:27:06,410845,002684142520170925185012,BO-20140726014851385,CT-20140726014851386,TKI_08,PDFA

In [29]:
print("No of Records with NULL book_code : ", len(df[df['book_code'].isnull()]))#10136500
df.book_code.fillna(df.contents_code, inplace=True)
print("After filling, No of Records with NULL book_code : ", len(df[df['book_code'].isnull()]))#0

No of Records with NULL book_code :  10136500
After filling, No of Records with NULL book_code :  0

In [30]:
df.sort_values(by='event_time', inplace=True)
df

,Unnamed: 0,row_id,trial_time,event_name,event_time,receipt_time,learner_id,session_id,book_code,contents_code,library_source,media_fm
8554747,8554748,00000000000662DE0000000000015243000000000535DC...,1970-01-01,book_open,1970-01-02 00:16:56,2017-09-14 08:03:34,86595,002458747020170914165325,CT-20170728150606442,CT-20170728150606442,TKE_01,TEPUB
6308098,6308099,00000000000662DE0000000000015243000000000535DC...,1970-01-01,book_first_open,1970-01-02 00:16:56,2017-09-14 08:03:34,86595,002458747020170914165325,CT-20170728150606442,CT-20170728150606442,TKE_01,TEPUB
4869331,4869332,00000000000662DE0000000000015243000000000535DC...,1970-01-01,book_complete,1970-01-02 00:16:56,2017-09-14 08:03:34,86595,002458747020170914165325,CT-20170728150606442,CT-20170728150606442,NaN,NaN
865162,865163,00000000000662DE0000000000015243000000000537C5...,1970-01-01,book_close,1970-01-02 00:19:01,2017-09-14 08:03:34,86595,002458747020170914165334,CT-20170728150606442,CT-20170728150606442,NaN,NaN
8554748,8554749,00000000000662DE00000000000152430000000005380B...,1970-01-01,book_open,1970-01-02 00:19:19,2017-09-14 08:03:34,86595,002458747020170914165334,CT-20170906155328365,CT-20170906155328365,TBU,TEPUB
6308320,6308321,00000000000662DE00000000000152430000000005380B...,1970-01-01,book_first_open,1970-01-02 00:19:19,2017-09-14 08:03:34,86595,002458747020170914165334,CT-20170906155328365,CT-20170906155328365,TBU,TEPUB
4869373,4869374,00000000000662DE00000000000152430000000005380B...,1970-01-01,book_complete,1970-01-02 00:19:19,2017-09-14 08:03:34,86595,002458747020170914165334,CT-20170906155328365,CT-20170906155328365,NaN,NaN
865248,865249,00000000000662DE000000000001524300000000053859...,1970-01-01,book_close,1970-01-02 00:19:39,2017-09-14 08:03:40,86595,002458747020170914165334,CT-20170906155328365,CT-20170906155328365,NaN,NaN
7845467,7845468,0000000000059C61000000000001A99800000134975E2A...,1970-01-01,book_first_open,2012-01-01 03:44:18,2017-09-14 12:49:10,108952,002485394120170914213911,CT-20170728163031742,CT-20170728163031742,TKE_03,TEPUB
11136620,11136621,0000000000059C61000000000001A99800000134975E2A...,1970-01-01,book_open,2012-01-01 03:44:18,2017-09-14 12:49:10,108952,002485394120170914213911,CT-20170728163031742,CT-20170728163031742,TKE_03,TEPUB
5644872,5644873,0000000000059C61000000000001A99800000134975E2A...,1970-01-01,book_complete,2012-01-01 03:44:18,2017-09-14 12:49:10,108952,002485394120170914213911,CT-20170728163031742,CT-20170728163031742,NaN,NaN
2801660,2801661,0000000000059C61000000000001A99800000134975E88...,1970-01-01,book_close,2012-01-01 03:44:42,2017-09-14 12:52:41,108952,002485394120170914213911,CT-20170728163031742,CT-20170728163031742,NaN,NaN
5853844,5853845,0000000000073BA100000000000809B40000013498C6ED...,1970-01-01,book_complete,2012-01-01 10:18:21,2017-09-14 10:58:53,526772,002722554820170810201134,CT-20170811164203228,CT-20170811164203228,NaN,NaN
11337575,11337576,0000000000073BA100000000000809B40000013498C6F1...,1970-01-01,book_open,2012-01-01 10:18:22,2017-09-14 10:58:53,526772,002722554820170810201134,CT-20170811164203228,CT-20170811164203228,TBE,TEPUB
7805135,7805136,0000000000073BA100000000000809B40000013498C6F1...,1970-01-01,book_first_open,2012-01-01 10:18:22,2017-09-14 10:58:53,526772,002722554820170810201134,CT-20170811164203228,CT-20170811164203228,TBE,TEPUB
11337715,11337716,0000000000073BA100000000000809B40000013498C8E1...,1970-01-01,book_open,2012-01-01 10:20:29,2017-09-14 10:58:59,526772,002722554820170810201134,CT-20170811164201289,CT-20170811164201289,TBE,TEPUB
7736741,7736742,0000000000073BA100000000000809B40000013498C8E1...,1970-01-01,book_first_open,2012-01-01 10:20:29,2017-09-14 10:58:59,526772,002722554820170810201134,CT-20170811164201289,CT-20170811164201289,TBE,TEPUB
5831476,5831477,0000000000073BA100000000000809B40000013498C8E1...,1970-01-01,book_complete,2012-01-01 10:20:29,2017-09-14 10:58:59,526772,002722554820170810201134,CT-20170811164201289,CT-20170811164201289,NaN,NaN
11070380,11070381,0000000000059C61000000000001A998000001349C80EC...,1970-01-01,book_open,2012-01-02 03:40:22,2017-09-15 12:47:47,108952,002485394120170915213520,CT-20170904174502994,CT-20170904174502994,TT,TEPUB
3099749,3099750,0000000000059C61000000000001A99800000134A1E5AD...,1970-01-01,book_close,2012-01-03 04:48:31,2017-09-16 13:53:09,108952,002485394120170916224115,CT-20170904174502994,CT-20170904174502994,NaN,NaN
9898994,9898995,0000000000059C61000000000001A99800000134A496FA...,1970-01-01,book_open,2012-01-03 17:21:25,2017-09-17 02:18:03,108952,002485394120170917111604,CT-20170906155328365,CT-20170906155328365,TBU,TEPUB
5595491,5595492,0000000000059C61000000000001A99800000134A496FA...,1970-01-01,book_complete,2012-01-03 17:21:25,2017-09-17 02:17:57,108952,002485394120170917111604,CT-20170906155328365,CT-20170906155328365,NaN,NaN
7704617,7704618,0000000000059C61000000000001A99800000134A496FA...,1970-01-01,book_first_open,2012-01-03 17:21:25,2017-09-17 02:17:57,108952,002485394120170917111604,CT-20170906155328365,CT-20170906155328365,TBU,TEPUB
14428982,14428983,0000000000059C61000000000001A99800000134A49A9F...,1970-01-01,video_close,2012-01-03 17:25:24,2017-09-17 02:32:56,108952,002485394120170917111604,BO-20170627173817922,NaN,NaN,NaN
3039384,3039385,0000000000059C61000000000001A99800000134A49B0D...,1970-01-01,book_close,2012-01-03 17:25:52,2017-09-17 02:33:01,108952,002485394120170917111604,CT-20170829173725795,CT-20170829173725795,NaN,NaN
18562738,18562739,0000000000059C61000000000001A99800000134A49B4F...,1970-01-01,video_first_open,2012-01-03 17:26:09,2017-09-17 02:33:06,108952,002485394120170917111604,CT-20170911155837615,CT-20170911155837615,TV,TMP4
7687289,7687290,0000000000059C61000000000001A99800000134A4A3AF...,1970-01-01,book_first_open,2012-01-03 17:35:18,2017-09-17 02:42:52,108952,002485394120170917111604,BO-20170424154817203,CT-20170424154817203,TM,PDFC
10104704,10104705,0000000000059C61000000000001A99800000134A4A3AF...,1970-01-01,book_open,2012-01-03 17:35:18,2017-09-17 02:42:52,108952,002485394120170917111604,BO-20170424154817203,CT-20170424154817203,TM,PDFC
10300148,10300149,0000000000059C61000000000001A99800000134A51F54...,1970-01-01,book_open,2012-01-03 19:50:21,2017-09-17 04:47:54,108952,002485394120170917134520,BO-20170424154817203,CT-20170424154817203,TM,PDFC
5745575,5745576,0000000000059C61000000000001A99800000134A5265D...,1970-01-01,book_complete,2012-01-03 19:58:02,2017-09-17 05:03:17,108952,002485394120170917134520,BO-20170424154817203,CT-20170424154817203,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
23559131,23559132,000000000006126A00000000000123BD0000015EBFF8DB...,1970-01-01,video_open,2017-09-26 20:55:11,2017-09-26 20:56:22,74685,002430069020170927054306,CT-20160324155232897,CT-20160324155232897,TC,TMP4
19368725,19368726,0000000000058D1F000000000000BDCF0000015EC1BCC3...,1970-01-01,video_first_open,2017-09-27 05:08:47,2017-09-26 05:11:35,48591,002361961520170926140713,BO-20170821132107208,CT-20170821132107208,TL,MP4
17269884,17269885,0000000000058D1F000000000000BDCF0000015EC1BDCC...,1970-01-01,video_close,2017-09-27 05:09:55,2017-09-26 05:11:37,48591,002361961520170926140713,BO-20170821132107208,CT-20170821132107208,NaN,NaN
5537876,5537877,0000000000066B80000000000000DA6D0000015F70CC50...,1970-01-01,book_complete,2017-10-31 04:59:19,2017-09-14 05:07:49,55917,002376627320170914135823,CT-20170829173725795,CT-20170829173725795,NaN,NaN
10101622,10101623,0000000000066B80000000000000DA6D0000015F70CC54...,1970-01-01,book_open,2017-10-31 04:59:20,2017-09-14 05:07:49,55917,002376627320170914135823,CT-20170829173725795,CT-20170829173725795,TBI,TEPUB
7234758,7234759,0000000000066B80000000000000DA6D0000015F70CC54...,1970-01-01,book_first_open,2017-10-31 04:59:20,2017-09-14 05:07:49,55917,002376627320170914135823,CT-20170829173725795,CT-20170829173725795,TBI,TEPUB
18577920,18577921,0000000000066B80000000000000DA6D0000015F70CCB2...,1970-01-01,video_first_open,2017-10-31 04:59:44,2017-09-14 05:07:49,55917,002376627320170914135823,BO-20170627173817922,NaN,TBI,MP4
14664594,14664595,0000000000066B80000000000000DA6D0000015F70CD1B...,1970-01-01,video_close,2017-10-31 05:00:11,2017-09-14 05:07:52,55917,002376627320170914135823,BO-20170627173817922,NaN,NaN,NaN
3337987,3337988,0000000000066B80000000000000DA6D0000015F711E6B...,1970-01-01,book_close,2017-10-31 06:29:00,2017-09-14 06:38:06,55917,002376627320170914152816,CT-20170829173725795,CT-20170829173725795,NaN,NaN
10970624,10970625,0000000000066B80000000000000DA6D0000015F711E7F...,1970-01-01,book_open,2017-10-31 06:29:05,2017-09-14 06:38:06,55917,002376627320170914152816,CT-20170829173725795,CT-20170829173725795,TBI,TEPUB
21495415,21495416,0000000000066B80000000000000DA6D0000015F711ED5...,1970-01-01,video_open,2017-10-31 06:29:27,2017-09-14 06:38:13,55917,002376627320170914152816,BO-20170627173817922,NaN,TBI,MP4
15928259,15928260,0000000000066B80000000000000DA6D0000015F712096...,1970-01-01,video_close,2017-10-31 06:31:22,2017-09-14 06:42:45,55917,002376627320170914152816,BO-20170627173817922,NaN,NaN,NaN
2672201,2672202,0000000000066B80000000000000DA6D0000015F712107...,1970-01-01,book_close,2017-10-31 06:31:51,2017-09-14 06:42:46,55917,002376627320170914152816,CT-20170829173725795,CT-20170829173725795,NaN,NaN
18987190,18987191,0000000000066B80000000000000DA6D0000015F7135B4...,1970-01-01,video_first_open,2017-10-31 06:54:26,2017-09-14 07:03:13,55917,002376627320170914155337,CT-20170830105310551,CT-20170830105310551,TBE,TMP4
15929059,15929060,0000000000066B80000000000000DA6D0000015F7135C4...,1970-01-01,video_close,2017-10-31 06:54:30,2017-09-14 07:03:13,55917,002376627320170914155337,CT-20170830105310551,CT-20170830105310551,NaN,NaN
11278029,11278030,0000000000066B80000000000000DA6D0000015F71363D...,1970-01-01,book_open,2017-10-31 06:55:01,2017-09-14 07:03:19,55917,002376627320170914155337,CT-20170829173725795,CT-20170829173725795,TBI,TEPUB
22233996,22233997,0000000000066B80000000000000DA6D0000015F713687...,1970-01-01,video_open,2017-10-31 06:55:20,2017-09-14 07:03:20,55917,002376627320170914155337,BO-20170627173817922,NaN,TBI,MP4
16301993,16301994,0000000000066B80000000000000DA6D0000015F71372F...,1970-01-01,video_close,2017-10-31 06:56:03,2017-09-14 07:07:41,55917,002376627320170914155337,BO-20170627173817922,NaN,NaN,NaN
2856810,2856811,0000000000066B80000000000000DA6D0000015F713781...,1970-01-01,book_close,2017-10-31 06:56:24,2017-09-14 07:07:48,55917,002376627320170914155337,CT-20170829173725795,CT-20170829173725795,NaN,NaN
5606596,5606597,0000000000066B80000000000000DA6D0000015F7BE4BC...,1970-01-01,book_complete,2017-11-02 08:41:49,2017-09-16 08:52:55,55917,002376627320170916174059,CT-20170728153841818,CT-20170728153841818,NaN,NaN
10728240,10728241,0000000000066B80000000000000DA6D0000015F7BE4BC...,1970-01-01,book_open,2017-11-02 08:41:49,2017-09-16 08:52:55,55917,002376627320170916174059,CT-20170728153841818,CT-20170728153841818,TKE_02,TEPUB
7318619,7318620,0000000000066B80000000000000DA6D0000015F7BE4BC...,1970-01-01,book_first_open,2017-11-02 08:41:49,2017-09-16 08:52:55,55917,002376627320170916174059,CT-20170728153841818,CT-20170728153841818,TKE_02,TEPUB
2726509,2726510,0000000000066B80000000000000DA6D0000015F7BE4CC...,1970-01-01,book_close,2017-11-02 08:41:53,2017-09-16 08:52:55,55917,002376627320170916174059,CT-20170728153841818,CT-20170728153841818,NaN,NaN
7422897,7422898,0000000000066B80000000000000DA6D0000015F7EE7A4...,1970-01-01,book_first_open,2017-11-02 22:43:51,2017-09-16 22:52:52,55917,002376627320170917074246,CT-20170825153314812,CT-20170825153314812,TKE_02,TEPUB
5692037,5692038,0000000000066B80000000000000DA6D0000015F7EE7A4...,1970-01-01,book_complete,2017-11-02 22:43:51,2017-09-16 22:52:52,55917,002376627320170917074246,CT-20170825153314812,CT-20170825153314812,NaN,NaN
9800111,9800112,0000000000066B80000000000000DA6D0000015F7EE7A4...,1970-01-01,book_open,2017-11-02 22:43:51,2017-09-16 22:52:52,55917,002376627320170917074246,CT-20170825153314812,CT-20170825153314812,TKE_02,TEPUB
2943451,2943452,0000000000066B80000000000000DA6D0000015F7EE8A2...,1970-01-01,book_close,2017-11-02 22:44:56,2017-09-16 22:52:57,55917,002376627320170917074246,CT-20170825153314812,CT-20170825153314812,NaN,NaN
3239952,3239953,0000000000066B80000000000000DA6D0000015F8153DD...,1970-01-01,book_close,2017-11-03 10:01:18,2017-09-17 10:12:58,55917,002376627320170917185616,CT-20170904174502994,CT-20170904174502994,NaN,NaN
21356090,21356091,0000000000066B80000000000000DA6D0000015FED9907...,1970-01-01,video_open,2017-11-24 10:35:50,2017-09-18 10:38:06,55917,002376627320170918193522,BO-20170627173622446,CT-20170627173622446,TN,MP4
14797198,14797199,0000000000066B80000000000000DA6D0000015FED9913...,1970-01-01,video_close,2017-11-24 10:35:53,2017-09-18 10:38:14,55917,002376627320170918193522,BO-20170627173622446,CT-20170627173622446,NaN,NaN

In [33]:
df.set_index(['learner_id', 'book_code'])

                                 Unnamed: 0  \
learner_id book_code
86595      CT-20170728150606442     8554748
           CT-20170728150606442     6308099
           CT-20170728150606442     4869332
           CT-20170728150606442      865163
           CT-20170906155328365     8554749
           CT-20170906155328365     6308321
           CT-20170906155328365     4869374
           CT-20170906155328365      865249
108952     CT-20170728163031742     7845468
           CT-20170728163031742    11136621
           CT-20170728163031742     5644873
           CT-20170728163031742     2801661
526772     CT-20170811164203228     5853845
           CT-20170811164203228    11337576
           CT-20170811164203228     7805136
           CT-20170811164201289    11337716
           CT-20170811164201289     7736742
           CT-20170811164201289     5831477
108952     CT-20170904174502994    11070381
           CT-20170904174502994     3099750
           CT-20170906155328365     9898995
           CT-20170906155328365     5595492
           CT-20170906155328365     7704618
           BO-20170627173817922    14428983
           CT-20170829173725795     3039385
           CT-20170911155837615    18562739
           BO-20170424154817203     7687290
           BO-20170424154817203    10104705
           BO-20170424154817203    10300149
           BO-20170424154817203     5745576
...                                     ...
74685      CT-20160324155232897    23559132
48591      BO-20170821132107208    19368726
           BO-20170821132107208    17269885
55917      CT-20170829173725795     5537877
           CT-20170829173725795    10101623
           CT-20170829173725795     7234759
           BO-20170627173817922    18577921
           BO-20170627173817922    14664595
           CT-20170829173725795     3337988
           CT-20170829173725795    10970625
           BO-20170627173817922    21495416
           BO-20170627173817922    15928260
           CT-20170829173725795     2672202
           CT-20170830105310551    18987191
           CT-20170830105310551    15929060
           CT-20170829173725795    11278030
           BO-20170627173817922    22233997
           BO-20170627173817922    16301994
           CT-20170829173725795     2856811
           CT-20170728153841818     5606597
           CT-20170728153841818    10728241
           CT-20170728153841818     7318620
           CT-20170728153841818     2726510
           CT-20170825153314812     7422898
           CT-20170825153314812     5692038
           CT-20170825153314812     9800112
           CT-20170825153314812     2943452
           CT-20170904174502994     3239953
           BO-20170627173622446    21356091
           BO-20170627173622446    14797199

                                                                            row_id  \
learner_id book_code
86595      CT-20170728150606442  00000000000662DE0000000000015243000000000535DC...
           CT-20170728150606442  00000000000662DE0000000000015243000000000535DC...
           CT-20170728150606442  00000000000662DE0000000000015243000000000535DC...
           CT-20170728150606442  00000000000662DE0000000000015243000000000537C5...
           CT-20170906155328365  00000000000662DE00000000000152430000000005380B...
           CT-20170906155328365  00000000000662DE00000000000152430000000005380B...
           CT-20170906155328365  00000000000662DE00000000000152430000000005380B...
           CT-20170906155328365  00000000000662DE000000000001524300000000053859...
108952     CT-20170728163031742  0000000000059C61000000000001A99800000134975E2A...
           CT-20170728163031742  0000000000059C61000000000001A99800000134975E2A...
           CT-20170728163031742  0000000000059C61000000000001A99800000134975E2A...
           CT-20170728163031742  0000000000059C61000000000001A99800000134975E88...
526772     CT-20170811164203228  0000000000073BA100000000000809B40000013498C6ED...
           CT-20170811164203228  0000000000073BA100000000000809B40000013498C6F1...
           CT-20170811164203228  0000000000073BA100000000000809B40000013498C6F1...
           CT-20170811164201289  0000000000073BA100000000000809B40000013498C8E1...
           CT-20170811164201289  0000000000073BA100000000000809B40000013498C8E1...
           CT-20170811164201289  0000000000073BA100000000000809B40000013498C8E1...
108952     CT-20170904174502994  0000000000059C61000000000001A998000001349C80EC...
           CT-20170904174502994  0000000000059C61000000000001A99800000134A1E5AD...
           CT-20170906155328365  0000000000059C61000000000001A99800000134A496FA...
           CT-20170906155328365  0000000000059C61000000000001A99800000134A496FA...
           CT-20170906155328365  0000000000059C61000000000001A99800000134A496FA...
           BO-20170627173817922  0000000000059C61000000000001A99800000134A49A9F...
           CT-20170829173725795  0000000000059C61000000000001A99800000134A49B0D...
           CT-20170911155837615  0000000000059C61000000000001A99800000134A49B4F...
           BO-20170424154817203  0000000000059C61000000000001A99800000134A4A3AF...
           BO-20170424154817203  0000000000059C61000000000001A99800000134A4A3AF...
           BO-20170424154817203  0000000000059C61000000000001A99800000134A51F54...
           BO-20170424154817203  0000000000059C61000000000001A99800000134A5265D...
...                                                                            ...
74685      CT-20160324155232897  000000000006126A00000000000123BD0000015EBFF8DB...
48591      BO-20170821132107208  0000000000058D1F000000000000BDCF0000015EC1BCC3...
           BO-20170821132107208  0000000000058D1F000000000000BDCF0000015EC1BDCC...
55917      CT-20170829173725795  0000000000066B80000000000000DA6D0000015F70CC50...
           CT-20170829173725795  0000000000066B80000000000000DA6D0000015F70CC54...
           CT-20170829173725795  0000000000066B80000000000000DA6D0000015F70CC54...
           BO-20170627173817922  0000000000066B80000000000000DA6D0000015F70CCB2...
           BO-20170627173817922  0000000000066B80000000000000DA6D0000015F70CD1B...
           CT-20170829173725795  0000000000066B80000000000000DA6D0000015F711E6B...
           CT-20170829173725795  0000000000066B80000000000000DA6D0000015F711E7F...
           BO-20170627173817922  0000000000066B80000000000000DA6D0000015F711ED5...
           BO-20170627173817922  0000000000066B80000000000000DA6D0000015F712096...
           CT-20170829173725795  0000000000066B80000000000000DA6D0000015F712107...
           CT-20170830105310551  0000000000066B80000000000000DA6D0000015F7135B4...
           CT-20170830105310551  0000000000066B80000000000000DA6D0000015F7135C4...
           CT-20170829173725795  0000000000066B80000000000000DA6D0000015F71363D...
           BO-20170627173817922  0000000000066B80000000000000DA6D0000015F713687...
           BO-20170627173817922  0000000000066B80000000000000DA6D0000015F71372F...
           CT-20170829173725795  0000000000066B80000000000000DA6D0000015F713781...
           CT-20170728153841818  0000000000066B80000000000000DA6D0000015F7BE4BC...
           CT-20170728153841818  0000000000066B80000000000000DA6D0000015F7BE4BC...
           CT-20170728153841818  0000000000066B80000000000000DA6D0000015F7BE4BC...
           CT-20170728153841818  0000000000066B80000000000000DA6D0000015F7BE4CC...
           CT-20170825153314812  0000000000066B80000000000000DA6D0000015F7EE7A4...
           CT-20170825153314812  0000000000066B80000000000000DA6D0000015F7EE7A4...
           CT-20170825153314812  0000000000066B80000000000000DA6D0000015F7EE7A4...
           CT-20170825153314812  0000000000066B80000000000000DA6D0000015F7EE8A2...
           CT-20170904174502994  0000000000066B80000000000000DA6D0000015F8153DD...
           BO-20170627173622446  0000000000066B80000000000000DA6D0000015FED9907...
           BO-20170627173622446  0000000000066B80000000000000DA6D0000015FED9913...

                                 trial_time        event_name  \
learner_id book_code
86595      CT-20170728150606442  1970-01-01         book_open
           CT-20170728150606442  1970-01-01   book_first_open
           CT-20170728150606442  1970-01-01     book_complete
           CT-20170728150606442  1970-01-01        book_close
           CT-20170906155328365  1970-01-01         book_open
           CT-20170906155328365  1970-01-01   book_first_open
           CT-20170906155328365  1970-01-01     book_complete
           CT-20170906155328365  1970-01-01        book_close
108952     CT-20170728163031742  1970-01-01   book_first_open
           CT-20170728163031742  1970-01-01         book_open
           CT-20170728163031742  1970-01-01     book_complete
           CT-20170728163031742  1970-01-01        book_close
526772     CT-20170811164203228  1970-01-01     book_complete
           CT-20170811164203228  1970-01-01         book_open
           CT-20170811164203228  1970-01-01   book_first_open
           CT-20170811164201289  1970-01-01         book_open
           CT-20170811164201289  1970-01-01   book_first_open
           CT-20170811164201289  1970-01-01     book_complete
108952     CT-20170904174502994  1970-01-01         book_open
           CT-20170904174502994  1970-01-01        book_close
           CT-20170906155328365  1970-01-01         book_open
           CT-20170906155328365  1970-01-01     book_complete
           CT-20170906155328365  1970-01-01   book_first_open
           BO-20170627173817922  1970-01-01       video_close
           CT-20170829173725795  1970-01-01        book_close
           CT-20170911155837615  1970-01-01  video_first_open
           BO-20170424154817203  1970-01-01   book_first_open
           BO-20170424154817203  1970-01-01         book_open
           BO-20170424154817203  1970-01-01         book_open
           BO-20170424154817203  1970-01-01     book_complete
...                                     ...               ...
74685      CT-20160324155232897  1970-01-01        video_open
48591      BO-20170821132107208  1970-01-01  video_first_open
           BO-20170821132107208  1970-01-01       video_close
55917      CT-20170829173725795  1970-01-01     book_complete
           CT-20170829173725795  1970-01-01         book_open
           CT-20170829173725795  1970-01-01   book_first_open
           BO-20170627173817922  1970-01-01  video_first_open
           BO-20170627173817922  1970-01-01       video_close
           CT-20170829173725795  1970-01-01        book_close
           CT-20170829173725795  1970-01-01         book_open
           BO-20170627173817922  1970-01-01        video_open
           BO-20170627173817922  1970-01-01       video_close
           CT-20170829173725795  1970-01-01        book_close
           CT-20170830105310551  1970-01-01  video_first_open
           CT-20170830105310551  1970-01-01       video_close
           CT-20170829173725795  1970-01-01         book_open
           BO-20170627173817922  1970-01-01        video_open
           BO-20170627173817922  1970-01-01       video_close
           CT-20170829173725795  1970-01-01        book_close
           CT-20170728153841818  1970-01-01     book_complete
           CT-20170728153841818  1970-01-01         book_open
           CT-20170728153841818  1970-01-01   book_first_open
           CT-20170728153841818  1970-01-01        book_close
           CT-20170825153314812  1970-01-01   book_first_open
           CT-20170825153314812  1970-01-01     book_complete
           CT-20170825153314812  1970-01-01         book_open
           CT-20170825153314812  1970-01-01        book_close
           CT-20170904174502994  1970-01-01        book_close
           BO-20170627173622446  1970-01-01        video_open
           BO-20170627173622446  1970-01-01       video_close

                                         event_time        receipt_time  \
learner_id book_code
86595      CT-20170728150606442 1970-01-02 00:16:56 2017-09-14 08:03:34
           CT-20170728150606442 1970-01-02 00:16:56 2017-09-14 08:03:34
           CT-20170728150606442 1970-01-02 00:16:56 2017-09-14 08:03:34
           CT-20170728150606442 1970-01-02 00:19:01 2017-09-14 08:03:34
           CT-20170906155328365 1970-01-02 00:19:19 2017-09-14 08:03:34
           CT-20170906155328365 1970-01-02 00:19:19 2017-09-14 08:03:34
           CT-20170906155328365 1970-01-02 00:19:19 2017-09-14 08:03:34
           CT-20170906155328365 1970-01-02 00:19:39 2017-09-14 08:03:40
108952     CT-20170728163031742 2012-01-01 03:44:18 2017-09-14 12:49:10
           CT-20170728163031742 2012-01-01 03:44:18 2017-09-14 12:49:10
           CT-20170728163031742 2012-01-01 03:44:18 2017-09-14 12:49:10
           CT-20170728163031742 2012-01-01 03:44:42 2017-09-14 12:52:41
526772     CT-20170811164203228 2012-01-01 10:18:21 2017-09-14 10:58:53
           CT-20170811164203228 2012-01-01 10:18:22 2017-09-14 10:58:53
           CT-20170811164203228 2012-01-01 10:18:22 2017-09-14 10:58:53
           CT-20170811164201289 2012-01-01 10:20:29 2017-09-14 10:58:59
           CT-20170811164201289 2012-01-01 10:20:29 2017-09-14 10:58:59
           CT-20170811164201289 2012-01-01 10:20:29 2017-09-14 10:58:59
108952     CT-20170904174502994 2012-01-02 03:40:22 2017-09-15 12:47:47
           CT-20170904174502994 2012-01-03 04:48:31 2017-09-16 13:53:09
           CT-20170906155328365 2012-01-03 17:21:25 2017-09-17 02:18:03
           CT-20170906155328365 2012-01-03 17:21:25 2017-09-17 02:17:57
           CT-20170906155328365 2012-01-03 17:21:25 2017-09-17 02:17:57
           BO-20170627173817922 2012-01-03 17:25:24 2017-09-17 02:32:56
           CT-20170829173725795 2012-01-03 17:25:52 2017-09-17 02:33:01
           CT-20170911155837615 2012-01-03 17:26:09 2017-09-17 02:33:06
           BO-20170424154817203 2012-01-03 17:35:18 2017-09-17 02:42:52
           BO-20170424154817203 2012-01-03 17:35:18 2017-09-17 02:42:52
           BO-20170424154817203 2012-01-03 19:50:21 2017-09-17 04:47:54
           BO-20170424154817203 2012-01-03 19:58:02 2017-09-17 05:03:17
...                                             ...                 ...
74685      CT-20160324155232897 2017-09-26 20:55:11 2017-09-26 20:56:22
48591      BO-20170821132107208 2017-09-27 05:08:47 2017-09-26 05:11:35
           BO-20170821132107208 2017-09-27 05:09:55 2017-09-26 05:11:37
55917      CT-20170829173725795 2017-10-31 04:59:19 2017-09-14 05:07:49
           CT-20170829173725795 2017-10-31 04:59:20 2017-09-14 05:07:49
           CT-20170829173725795 2017-10-31 04:59:20 2017-09-14 05:07:49
           BO-20170627173817922 2017-10-31 04:59:44 2017-09-14 05:07:49
           BO-20170627173817922 2017-10-31 05:00:11 2017-09-14 05:07:52
           CT-20170829173725795 2017-10-31 06:29:00 2017-09-14 06:38:06
           CT-20170829173725795 2017-10-31 06:29:05 2017-09-14 06:38:06
           BO-20170627173817922 2017-10-31 06:29:27 2017-09-14 06:38:13
           BO-20170627173817922 2017-10-31 06:31:22 2017-09-14 06:42:45
           CT-20170829173725795 2017-10-31 06:31:51 2017-09-14 06:42:46
           CT-20170830105310551 2017-10-31 06:54:26 2017-09-14 07:03:13
           CT-20170830105310551 2017-10-31 06:54:30 2017-09-14 07:03:13
           CT-20170829173725795 2017-10-31 06:55:01 2017-09-14 07:03:19
           BO-20170627173817922 2017-10-31 06:55:20 2017-09-14 07:03:20
           BO-20170627173817922 2017-10-31 06:56:03 2017-09-14 07:07:41
           CT-20170829173725795 2017-10-31 06:56:24 2017-09-14 07:07:48
           CT-20170728153841818 2017-11-02 08:41:49 2017-09-16 08:52:55
           CT-20170728153841818 2017-11-02 08:41:49 2017-09-16 08:52:55
           CT-20170728153841818 2017-11-02 08:41:49 2017-09-16 08:52:55
           CT-20170728153841818 2017-11-02 08:41:53 2017-09-16 08:52:55
           CT-20170825153314812 2017-11-02 22:43:51 2017-09-16 22:52:52
           CT-20170825153314812 2017-11-02 22:43:51 2017-09-16 22:52:52
           CT-20170825153314812 2017-11-02 22:43:51 2017-09-16 22:52:52
           CT-20170825153314812 2017-11-02 22:44:56 2017-09-16 22:52:57
           CT-20170904174502994 2017-11-03 10:01:18 2017-09-17 10:12:58
           BO-20170627173622446 2017-11-24 10:35:50 2017-09-18 10:38:06
           BO-20170627173622446 2017-11-24 10:35:53 2017-09-18 10:38:14

                                               session_id  \
learner_id book_code
86595      CT-20170728150606442  002458747020170914165325
           CT-20170728150606442  002458747020170914165325
           CT-20170728150606442  002458747020170914165325
           CT-20170728150606442  002458747020170914165334
           CT-20170906155328365  002458747020170914165334
           CT-20170906155328365  002458747020170914165334
           CT-20170906155328365  002458747020170914165334
           CT-20170906155328365  002458747020170914165334
108952     CT-20170728163031742  002485394120170914213911
           CT-20170728163031742  002485394120170914213911
           CT-20170728163031742  002485394120170914213911
           CT-20170728163031742  002485394120170914213911
526772     CT-20170811164203228  002722554820170810201134
           CT-20170811164203228  002722554820170810201134
           CT-20170811164203228  002722554820170810201134
           CT-20170811164201289  002722554820170810201134
           CT-20170811164201289  002722554820170810201134
           CT-20170811164201289  002722554820170810201134
108952     CT-20170904174502994  002485394120170915213520
           CT-20170904174502994  002485394120170916224115
           CT-20170906155328365  002485394120170917111604
           CT-20170906155328365  002485394120170917111604
           CT-20170906155328365  002485394120170917111604
           BO-20170627173817922  002485394120170917111604
           CT-20170829173725795  002485394120170917111604
           CT-20170911155837615  002485394120170917111604
           BO-20170424154817203  002485394120170917111604
           BO-20170424154817203  002485394120170917111604
           BO-20170424154817203  002485394120170917134520
           BO-20170424154817203  002485394120170917134520
...                                                   ...
74685      CT-20160324155232897  002430069020170927054306
48591      BO-20170821132107208  002361961520170926140713
           BO-20170821132107208  002361961520170926140713
55917      CT-20170829173725795  002376627320170914135823
           CT-20170829173725795  002376627320170914135823
           CT-20170829173725795  002376627320170914135823
           BO-20170627173817922  002376627320170914135823
           BO-20170627173817922  002376627320170914135823
           CT-20170829173725795  002376627320170914152816
           CT-20170829173725795  002376627320170914152816
           BO-20170627173817922  002376627320170914152816
           BO-20170627173817922  002376627320170914152816
           CT-20170829173725795  002376627320170914152816
           CT-20170830105310551  002376627320170914155337
           CT-20170830105310551  002376627320170914155337
           CT-20170829173725795  002376627320170914155337
           BO-20170627173817922  002376627320170914155337
           BO-20170627173817922  002376627320170914155337
           CT-20170829173725795  002376627320170914155337
           CT-20170728153841818  002376627320170916174059
           CT-20170728153841818  002376627320170916174059
           CT-20170728153841818  002376627320170916174059
           CT-20170728153841818  002376627320170916174059
           CT-20170825153314812  002376627320170917074246
           CT-20170825153314812  002376627320170917074246
           CT-20170825153314812  002376627320170917074246
           CT-20170825153314812  002376627320170917074246
           CT-20170904174502994  002376627320170917185616
           BO-20170627173622446  002376627320170918193522
           BO-20170627173622446  002376627320170918193522

                                        contents_code library_source media_fm

In [6]:
filters = (df['event_name'] == 'book_open') | (df['event_name'] == 'book_close')
df[filters]

,Unnamed: 0,row_id,trial_time,event_name,event_time,receipt_time,learner_id,session_id,book_code,contents_code,library_source,media_fm
865032,865033,000000000007E1DA00000000000A04400000015E9EEEF4...,1970-01-01,book_close,2017-09-20 10:56:54,2017-09-20 11:05:38,656448,002737730320170920195238,BO-20160329135654842,CT-20160329135654842,NaN,NaN
865033,865034,000000000002097E000000000004B9360000015EA3E7E4...,1970-01-01,book_close,2017-09-21 10:07:17,2017-09-21 11:35:20,309558,002651290020170921202622,BO-20140726015827440,CT-20140726015827440,NaN,NaN
865034,865035,00000000000737CB00000000000801710000015E99D09F...,1970-01-01,book_close,2017-09-19 11:05:40,2017-09-19 11:15:09,524657,002722362020170919193114,NaN,CT-20170803104202549,NaN,NaN
865035,865036,00000000000696A4000000000001DF470000015E9EEEF4...,1970-01-01,book_close,2017-09-20 10:56:54,2017-09-20 11:05:38,122695,002506813220170920194249,NaN,CT-20170728144711627,NaN,NaN
865036,865037,000000000004E0A300000000000643100000015E94D013...,1970-01-01,book_close,2017-09-18 11:46:58,2017-09-18 11:48:40,410384,002683202620170918204322,NaN,CT-20170728164232798,NaN,NaN
865037,865038,000000000006FF10000000000007BE170000015EA43047...,1970-01-01,book_close,2017-09-21 11:26:21,2017-09-21 11:35:26,507415,002716696220170921200604,BO-20140726015530182,NaN,NaN,NaN
865038,865039,000000000007760F000000000003438F0000015E99D0C6...,1970-01-01,book_close,2017-09-19 11:05:50,2017-09-19 11:15:09,213903,002607117620170919200022,NaN,CT-20170829173725795,NaN,NaN
865039,865040,0000000000058B6C000000000006D8890000015EA430D0...,1970-01-01,book_close,2017-09-21 11:26:56,2017-09-21 11:35:28,448649,002695183820170921202615,NaN,CT-20170829163010016,NaN,NaN
865040,865041,000000000007BBA6000000000009D1B70000015E9EEF27...,1970-01-01,book_close,2017-09-20 10:57:07,2017-09-20 11:05:40,643511,002733648520170920195337,BO-20140726015056775,CT-20140726015056775,NaN,NaN
865041,865042,00000000000353D300000000000813EB0000015E902F69...,1970-01-01,book_close,2017-09-17 14:13:00,2017-09-17 14:22:57,529387,002726334720170917230825,BO-20140726014903467,CT-20140726014903467,NaN,NaN
865042,865043,000000000006FC5E000000000007E8070000015EA43089...,1970-01-01,book_close,2017-09-21 11:26:38,2017-09-21 11:35:30,518151,002719432120170921201406,BO-20160421094137757,NaN,NaN,NaN
865043,865044,000000000005BE14000000000006F74C0000015E9EEF46...,1970-01-01,book_close,2017-09-20 10:57:15,2017-09-20 11:05:43,456524,002698863820170920194755,BO-20140726014749452,NaN,NaN,NaN
865044,865045,000000000001E98A000000000002AF060000015EA43081...,1970-01-01,book_close,2017-09-21 11:26:36,2017-09-21 11:35:30,175878,002571153620170921202245,BO-20140726014730319,CT-20140726014730319,NaN,NaN
865045,865046,000000000007AB5E000000000009BF8C0000015EA43072...,1970-01-01,book_close,2017-09-21 11:26:32,2017-09-21 11:35:33,638860,002730087320170921201332,BO-20170526154709672,CT-20170526154709672,NaN,NaN
865046,865047,000000000007AB5E000000000009BF8C0000015EA43095...,1970-01-01,book_close,2017-09-21 11:26:41,2017-09-21 11:35:33,638860,002730087320170921201332,NaN,CT-20170914151016389,NaN,NaN
865047,865048,000000000003A2CB0000000000027A300000015EA43008...,1970-01-01,book_close,2017-09-21 11:26:05,2017-09-21 11:35:18,162352,002560748420170921201314,BO-20160329135654842,CT-20160329135654842,NaN,NaN
865048,865049,000000000004ACA60000000000062F8A0000015E9EEEAA...,1970-01-01,book_close,2017-09-20 10:56:35,2017-09-20 11:05:32,405386,002682249520170920185645,BO-20150417014719989,CT-20150417014719989,NaN,NaN
865049,865050,000000000001CE83000000000004A8CF0000015EA4307A...,1970-01-01,book_close,2017-09-21 11:26:34,2017-09-21 11:35:20,305359,002650319020170921201932,BO-20170724102316502,CT-20170724102316502,NaN,NaN
865050,865051,0000000000000EED000000000007C5990000015E99D090...,1970-01-01,book_close,2017-09-19 11:05:36,2017-09-19 11:15:05,509337,002715660020170919200305,BO-20150417050400895,CT-20150417050400895,NaN,NaN
865051,865052,000000000003B26B000000000005ABD00000015EA43091...,1970-01-01,book_close,2017-09-21 11:26:40,2017-09-21 11:35:21,371664,002671824020170921202303,NaN,CT-20170831093949958,NaN,NaN
865052,865053,000000000007D5FC000000000009F5220000015E9EEEA6...,1970-01-01,book_close,2017-09-20 10:56:34,2017-09-20 11:05:33,652578,002736355920170920195459,BO-20140726014932682,NaN,NaN,NaN
865053,865054,000000000006ADEF00000000000786B90000015EA43024...,1970-01-01,book_close,2017-09-21 11:26:12,2017-09-21 11:35:22,493241,002711534520170921194917,NaN,CT-20170829174223880,NaN,NaN
865054,865055,000000000003F31A000000000004B6930000015E9EEF10...,1970-01-01,book_close,2017-09-20 10:57:01,2017-09-20 11:05:36,308883,002651877020170920193844,NaN,CT-20170914151009095,NaN,NaN
865055,865056,000000000002D6CD00000000000858000000015E99D090...,1970-01-01,book_close,2017-09-19 11:05:36,2017-09-19 11:15:05,546816,EC1A00445920170919200514,NaN,CT-20170829173725795,NaN,NaN
865056,865057,000000000003F4B5000000000001DEFB0000015EA4304B...,1970-01-01,book_close,2017-09-21 11:26:22,2017-09-21 11:35:27,122619,002504675320170921200822,BO-20170526154709682,CT-20170526154709682,NaN,NaN
865057,865058,000000000007E11400000000000A01640000015E9EEED5...,1970-01-01,book_close,2017-09-20 10:56:46,2017-09-20 11:05:36,655716,002737476920170920193359,BO-20140726020021275,NaN,NaN,NaN
865058,865059,000000000005705B000000000001F33C0000015EA430F3...,1970-01-01,book_close,2017-09-21 11:27:05,2017-09-21 11:35:29,127804,002516921520170921202655,BO-20161226152837329,CT-20161226152837329,NaN,NaN
865059,865060,0000000000055840000000000004E88F0000015E9EEEED...,1970-01-01,book_close,2017-09-20 10:56:52,2017-09-20 11:05:37,321679,002655223520170920195357,NaN,CT-20170829174223880,NaN,NaN
865060,865061,000000000005D63B00000000000710170000015EA43081...,1970-01-01,book_close,2017-09-21 11:26:36,2017-09-21 11:35:32,462871,002700017720170921200756,BO-20140726015530182,NaN,NaN,NaN
865061,865062,000000000006A0AF00000000000793A30000015E94D01F...,1970-01-01,book_close,2017-09-18 11:47:01,2017-09-18 11:48:40,496547,002711840620170918191335,BO-20140726014850379,CT-20140726014850379,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12595947,12595948,000000000002EF7F00000000000521B90000015EBE4B6E...,1970-01-01,book_open,2017-09-26 13:06:08,2017-09-26 13:11:40,336313,002659252620170926214717,BO-20161026112937419,CT-20161026112937419,LKWRD,PDFA
12595948,12595949,0000000000002DF50000000000021D000000015EBE4B62...,1970-01-01,book_open,2017-09-26 13:06:05,2017-09-26 13:11:35,138496,002531322620170926220540,NaN,CT-20161024153912425,TM,TPDFC
12595949,12595950,000000000001AB740000000000049AD10000015EBE4B14...,1970-01-01,book_open,2017-09-26 13:05:45,2017-09-26 13:11:34,301777,002648984920170926213420,NaN,CT-20170518142246638,TBI,TEPUB
12595950,12595951,000000000007A25E000000000009BC070000015EBE4B7D...,1970-01-01,book_open,2017-09-26 13:06:12,2017-09-26 13:11:42,637959,002731340020170926220145,BO-20170124130855959,CT-20170124130855959,LNTOD,EPUB
12595951,12595952,000000000006DCCA0000000000078E050000015EBE4DDF...,1970-01-01,book_open,2017-09-26 13:08:48,2017-09-26 13:12:19,495109,002711314620170926220552,BO-20140726015530182,NaN,EN,PDFA
12595952,12595953,000000000001E4C8000000000000E2480000015EBE4DBF...,1970-01-01,book_open,2017-09-26 13:08:40,2017-09-26 13:12:14,57928,002390928020170926215633,BO-20160530143321711,CT-20160530143321711,LA,PDFC
12595953,12595954,000000000007A64E000000000009B5BF0000015EBE4F36...,1970-01-01,book_open,2017-09-26 13:10:16,2017-09-26 13:16:24,636351,002647180920170926220821,NaN,CT-20170829175003233,TBI,TEPUB
12595954,12595955,000000000007C903000000000009E3EB0000015EBE50D8...,1970-01-01,book_open,2017-09-26 13:12:03,2017-09-26 13:16:48,648171,002734830220170926220325,BO-20150417014719940,CT-20150417014719940,TKI_08,EPUB
12595955,12595956,0000000000045E86000000000005EBF30000015EBE545B...,1970-01-01,book_open,2017-09-26 13:15:53,2017-09-26 13:21:33,388083,002677727320170926210509,BO-20170526154709685,CT-20170526154709685,TM,PDFC
12595956,12595957,0000000000017A5A000000000001D6710000015EBE5482...,1970-01-01,book_open,2017-09-26 13:16:03,2017-09-26 13:21:38,120433,002509338520170926221436,BO-20140726013603880,NaN,LY,PDFA
12595957,12595958,000000000005DE8000000000000257420000015EBE5568...,1970-01-01,book_open,2017-09-26 13:17:02,2017-09-26 13:21:49,153410,002549654420170926221329,NaN,CT-20170829175003233,TBI,TEPUB
12595958,12595959,000000000003DA7C000000000005B8F60000015EBE5987...,1970-01-01,book_open,2017-09-26 13:21:32,2017-09-26 13:26:45,375030,002673614220170926222112,BO-20170526160702934,CT-20170526160702934,LI,PDFA
12595959,12595960,000000000007011D000000000007F65B0000015EBE5AFA...,1970-01-01,book_open,2017-09-26 13:23:07,2017-09-26 13:26:59,521819,002720598820170926220727,BO-20170324113040183,CT-20170324113040183,LS,PDF
12595960,12595961,000000000006110B000000000005CA870000015EBE5BD5...,1970-01-01,book_open,2017-09-26 13:24:03,2017-09-26 13:27:18,379527,002674924520170926221924,NaN,CT-20170829175015315,TBI,TPDF
12595961,12595962,000000000001306F00000000000418650000015EBE5FD0...,1970-01-01,book_open,2017-09-26 13:28:24,2017-09-26 13:31:59,268389,002637011020170926222004,NaN,CT-20160324155302588,TC,TEPUB
12595962,12595963,000000000007D0B4000000000009EE410000015EBE66D1...,1970-01-01,book_open,2017-09-26 13:36:03,2017-09-26 13:41:33,650817,002735671420170926223440,NaN,CT-20170228104816218,TTR,TEPUB
12595963,12595964,000000000000C96B00000000000185170000015EBE6812...,1970-01-01,book_open,2017-09-26 13:37:25,2017-09-26 13:41:46,99607,002476997920170926223022,BO-20150417044757402,CT-20150417044757402,TKE_04,PDF
12595964,12595965,00000000000090C0000000000002120D0000015EBE67EA...,1970-01-01,book_open,2017-09-26 13:37:15,2017-09-26 13:41:47,135693,002525024020170926222240,NaN,CT-20170829175007870,TBI,TEPUB
12595965,12595966,0000000000040732000000000004CE640000015EBE6908...,1970-01-01,book_open,2017-09-26 13:38:28,2017-09-26 13:41:56,314980,002653411220170926221842,NaN,CT-20170914151016389,TBE,TEPUB
12595966,12595967,00000000000380D1000000000007E68F0000015EBE6913...,1970-01-01,book_open,2017-09-26 13:38:31,2017-09-26 13:42:03,517775,002718964220170926221001,NaN,CT-20170829175003233,TBI,TEPUB
12595967,12595968,0000000000023E91000000000005B42F0000015EBE6B07...,1970-01-01,book_open,2017-09-26 13:40:39,2017-09-26 13:46:24,373807,002671982320170926223753,BO-20140726015059296,CT-20140726015059296,LI,PDFA
12595968,12595969,000000000007F45600000000000A1E840000015EBE77B9...,1970-01-01,book_open,2017-09-26 13:54:31,2017-09-26 13:56:59,663172,002726848120170926224958,BO-20151222150610086,NaN,LV,PDF
12595969,12595970,000000000007320C000000000007BDAB0000015EBE9023...,1970-01-01,book_open,2017-09-26 14:21:11,2017-09-26 14:26:27,507307,002716279920170926231838,NaN,CT-20170725163928449,TKI_09,TEPUB
12595970,12595971,000000000007FBA000000000000A28F90000015EBE916F...,1970-01-01,book_open,2017-09-26 14:22:36,2017-09-26 14:26:37,665849,002733028320170926232231,BO-20161117144100805,NaN,ER,EPUB
12595971,12595972,000000000002090D0000000000086EF50000015EBE97D4...,1970-01-01,book_open,2017-09-26 14:29:35,2017-09-26 14:41:30,552693,EC3000000720170926233255,NaN,CT-20170830163841945,TV,TEPUB
12595972,12595973,000000000000D60C0000000000033FE30000015EBEA7E1...,1970-01-01,book_open,2017-09-26 14:47:07,2017-09-26 14:51:30,212963,002604269020170926233515,BO-20140726015823412,CT-20140726015823412,LI,PDFA
12595973,12595974,000000000000AB87000000000001A2430000015EBEA90E...,1970-01-01,book_open,2017-09-26 14:48:24,2017-09-26 14:51:36,107075,002489328120170926234748,BO-20140726020131783,NaN,LK,PDFA
12595974,12595975,000000000006169000000000000585510000015EBE238B...,1970-01-01,book_open,2017-09-26 12:22:34,2017-09-26 14:56:23,361809,002668478420170926235002,BO-20170124180543504,CT-20170124180543504,TBI,PDF
12595975,12595976,00000000000007EC000000000003E0680000015EBEC0A9...,1970-01-01,book_open,2017-09-26 15:14:11,2017-09-26 15:16:32,254056,002631752720170927001127,BO-20150417025554805,NaN,LI,PDFA
12595976,12595977,000000000000318A000000000002108C0000015EBEC7ED...,1970-01-01,book_open,2017-09-26 15:22:07,2017-09-26 15:26:30,135308,002521649020170926194948,NaN,CT-20170811164158476,TBE,TEPUB

In [35]:
filters = (df['learner_id'] == 55917) & (df['book_code'] == 'CT-20170829173725795')
df[filters].sort_values(by='event_time')

,Unnamed: 0,row_id,trial_time,event_name,event_time,receipt_time,learner_id,session_id,book_code,contents_code,library_source,media_fm
5537876,5537877,0000000000066B80000000000000DA6D0000015F70CC50...,1970-01-01,book_complete,2017-10-31 04:59:19,2017-09-14 05:07:49,55917,002376627320170914135823,CT-20170829173725795,CT-20170829173725795,NaN,NaN
10101622,10101623,0000000000066B80000000000000DA6D0000015F70CC54...,1970-01-01,book_open,2017-10-31 04:59:20,2017-09-14 05:07:49,55917,002376627320170914135823,CT-20170829173725795,CT-20170829173725795,TBI,TEPUB
7234758,7234759,0000000000066B80000000000000DA6D0000015F70CC54...,1970-01-01,book_first_open,2017-10-31 04:59:20,2017-09-14 05:07:49,55917,002376627320170914135823,CT-20170829173725795,CT-20170829173725795,TBI,TEPUB
3337987,3337988,0000000000066B80000000000000DA6D0000015F711E6B...,1970-01-01,book_close,2017-10-31 06:29:00,2017-09-14 06:38:06,55917,002376627320170914152816,CT-20170829173725795,CT-20170829173725795,NaN,NaN
10970624,10970625,0000000000066B80000000000000DA6D0000015F711E7F...,1970-01-01,book_open,2017-10-31 06:29:05,2017-09-14 06:38:06,55917,002376627320170914152816,CT-20170829173725795,CT-20170829173725795,TBI,TEPUB
2672201,2672202,0000000000066B80000000000000DA6D0000015F712107...,1970-01-01,book_close,2017-10-31 06:31:51,2017-09-14 06:42:46,55917,002376627320170914152816,CT-20170829173725795,CT-20170829173725795,NaN,NaN
11278029,11278030,0000000000066B80000000000000DA6D0000015F71363D...,1970-01-01,book_open,2017-10-31 06:55:01,2017-09-14 07:03:19,55917,002376627320170914155337,CT-20170829173725795,CT-20170829173725795,TBI,TEPUB
2856810,2856811,0000000000066B80000000000000DA6D0000015F713781...,1970-01-01,book_close,2017-10-31 06:56:24,2017-09-14 07:07:48,55917,002376627320170914155337,CT-20170829173725795,CT-20170829173725795,NaN,NaN

In [12]:
df[df['learner_id'] == 336313].sort_values(by='event_time')

,Unnamed: 0,row_id,trial_time,event_name,event_time,receipt_time,learner_id,session_id,book_code,contents_code,library_source,media_fm
1693465,1693466,000000000002EF7F00000000000521B90000015E7DAB39...,1970-01-01,book_close,2017-09-13 23:55:27,2017-09-14 00:07:37,336313,002659252620170914071835,BO-20170821132106980,NaN,NaN,NaN
1691466,1691467,000000000002EF7F00000000000521B90000015E7DAB70...,1970-01-01,book_close,2017-09-13 23:55:41,2017-09-14 00:07:37,336313,002659252620170914071835,NaN,CT-20170830164236439,NaN,NaN
8974644,8974645,000000000002EF7F00000000000521B90000015E7DAB9B...,1970-01-01,book_open,2017-09-13 23:55:52,2017-09-14 00:07:46,336313,002659252620170914071835,NaN,CT-20170830164235269,TV,TEPUB
1718566,1718567,000000000002EF7F00000000000521B90000015E7DACA0...,1970-01-01,book_close,2017-09-13 23:56:59,2017-09-14 00:07:50,336313,002659252620170914071835,NaN,CT-20170830164235269,NaN,NaN
9003492,9003493,000000000002EF7F00000000000521B90000015E7DACC0...,1970-01-01,book_open,2017-09-13 23:57:07,2017-09-14 00:07:50,336313,002659252620170914071835,NaN,CT-20170829173728813,TBI,TEPUB
1840483,1840484,000000000002EF7F00000000000521B90000015E7DAF92...,1970-01-01,book_close,2017-09-14 00:00:12,2017-09-14 00:12:38,336313,002659252620170914071835,NaN,CT-20170829173728813,NaN,NaN
9057866,9057867,000000000002EF7F00000000000521B90000015E7DAFF0...,1970-01-01,book_open,2017-09-14 00:00:36,2017-09-14 00:12:39,336313,002659252620170914071835,BO-20140726014901958,CT-20140726014901958,TKI_09,PDFA
1893264,1893265,000000000002EF7F00000000000521B90000015E7DB301...,1970-01-01,book_close,2017-09-14 00:03:57,2017-09-14 00:13:00,336313,002659252620170914071835,BO-20140726014901958,CT-20140726014901958,NaN,NaN
5274379,5274380,000000000002EF7F00000000000521B90000015E7DB478...,1970-01-01,book_complete,2017-09-14 00:05:33,2017-09-14 00:17:41,336313,002659252620170914071835,BO-20160329105829361,NaN,NaN,NaN
6942640,6942641,000000000002EF7F00000000000521B90000015E7DB478...,1970-01-01,book_first_open,2017-09-14 00:05:33,2017-09-14 00:17:41,336313,002659252620170914071835,BO-20160329105829361,NaN,LG,EPUB
9107393,9107394,000000000002EF7F00000000000521B90000015E7DB478...,1970-01-01,book_open,2017-09-14 00:05:33,2017-09-14 00:17:41,336313,002659252620170914071835,BO-20160329105829361,NaN,LG,EPUB
3317654,3317655,000000000002EF7F00000000000521B90000015E7DB728...,1970-01-01,book_close,2017-09-14 00:08:29,2017-09-14 00:17:54,336313,002659252620170914071835,BO-20160329105829361,NaN,NaN,NaN
9191341,9191342,000000000002EF7F00000000000521B90000015E7DB737...,1970-01-01,book_open,2017-09-14 00:08:33,2017-09-14 00:17:54,336313,002659252620170914071835,BO-20140726015530182,CT-20140726015530182,LK,PDFA
10983645,10983646,000000000002EF7F00000000000521B90000015E805AB5...,1970-01-01,book_open,2017-09-14 12:26:22,2017-09-14 12:38:05,336313,002659252620170914212603,BO-20140726014903971,NaN,EN,PDFA
2952571,2952572,000000000002EF7F00000000000521B90000015E805F2E...,1970-01-01,book_close,2017-09-14 12:31:15,2017-09-14 12:42:59,336313,002659252620170914212603,BO-20140726014903971,NaN,NaN,NaN
11003661,11003662,000000000002EF7F00000000000521B90000015E805F4D...,1970-01-01,book_open,2017-09-14 12:31:23,2017-09-14 12:42:59,336313,002659252620170914212603,NaN,CT-20170829173728813,TBI,TEPUB
3589458,3589459,000000000002EF7F00000000000521B90000015E806197...,1970-01-01,book_close,2017-09-14 12:33:53,2017-09-14 12:43:52,336313,002659252620170914212603,NaN,CT-20170829173728813,NaN,NaN
11117537,11117538,000000000002EF7F00000000000521B90000015E8061B2...,1970-01-01,book_open,2017-09-14 12:34:00,2017-09-14 12:43:59,336313,002659252620170914212603,NaN,CT-20170829173732748,TBI,TEPUB
3605489,3605490,000000000002EF7F00000000000521B90000015E8062CC...,1970-01-01,book_close,2017-09-14 12:35:12,2017-09-14 12:47:39,336313,002659252620170914212603,NaN,CT-20170829173732748,NaN,NaN
2783232,2783233,000000000002EF7F00000000000521B90000015E806360...,1970-01-01,book_close,2017-09-14 12:35:50,2017-09-14 12:47:53,336313,002659252620170914212603,NaN,CT-20170725151547379,NaN,NaN
11163042,11163043,000000000002EF7F00000000000521B90000015E80639B...,1970-01-01,book_open,2017-09-14 12:36:05,2017-09-14 12:47:52,336313,002659252620170914212603,BO-20140726015530182,CT-20140726015530182,LK,PDFA
10372049,10372050,000000000002EF7F00000000000521B90000015E8063C2...,1970-01-01,book_open,2017-09-14 12:36:15,2017-09-14 12:47:59,336313,002659252620170914212603,BO-20160329105829361,NaN,LG,EPUB
3457968,3457969,000000000002EF7F00000000000521B90000015E80662F...,1970-01-01,book_close,2017-09-14 12:38:54,2017-09-14 12:48:48,336313,002659252620170914212603,BO-20160329105829361,NaN,NaN,NaN
11176654,11176655,000000000002EF7F00000000000521B90000015E806646...,1970-01-01,book_open,2017-09-14 12:39:00,2017-09-14 12:48:49,336313,002659252620170914212603,BO-20140726015530182,CT-20140726015530182,LK,PDFA
11050391,11050392,000000000002EF7F00000000000521B90000015E80665E...,1970-01-01,book_open,2017-09-14 12:39:06,2017-09-14 12:48:49,336313,002659252620170914212603,BO-20140726015530182,CT-20140726015530182,LK,PDFA
3458305,3458306,000000000002EF7F00000000000521B90000015E8069C1...,1970-01-01,book_close,2017-09-14 12:42:48,2017-09-14 12:53:22,336313,002659252620170914212603,BO-20140726015530182,CT-20140726015530182,NaN,NaN
10867483,10867484,000000000002EF7F00000000000521B90000015E806A22...,1970-01-01,book_open,2017-09-14 12:43:13,2017-09-14 12:53:26,336313,002659252620170914212603,BO-20140726014850882,NaN,EN,PDFA
19595184,19595185,000000000002EF7F00000000000521B90000015E82CD6B...,1970-01-01,video_open,2017-09-14 23:50:54,2017-09-15 00:02:48,336313,002659252620170915085037,BO-20170718174924835,NaN,LBNEW,MP4
12726437,12726438,000000000002EF7F00000000000521B90000015E82CDBD...,1970-01-01,video_close,2017-09-14 23:51:15,2017-09-15 00:02:49,336313,002659252620170915085037,BO-20170718174924835,NaN,NaN,NaN
19549871,19549872,000000000002EF7F00000000000521B90000015E82CDBD...,1970-01-01,video_open,2017-09-14 23:51:15,2017-09-15 00:02:49,336313,002659252620170915085037,BO-20170718174924596,NaN,LBNEW,MP4
...,...,...,...,...,...,...,...,...,...,...,...,...
19343088,19343089,000000000002EF7F00000000000521B90000015EBB94D9...,1970-01-01,video_first_open,2017-09-26 00:27:28,2017-09-26 00:31:27,336313,002659252620170926092259,BO-20150728165840110,NaN,LKWRD,MP4A
17894094,17894095,000000000002EF7F00000000000521B90000015EBB99AB...,1970-01-01,video_close,2017-09-26 00:32:44,2017-09-26 00:36:28,336313,002659252620170926092259,BO-20150728165840110,NaN,NaN,NaN
19390852,19390853,000000000002EF7F00000000000521B90000015EBB9A15...,1970-01-01,video_first_open,2017-09-26 00:33:11,2017-09-26 00:36:28,336313,002659252620170926092259,NaN,CT-20161118150202875,TC,TMP4
17827429,17827430,000000000002EF7F00000000000521B90000015EBB9AB5...,1970-01-01,video_close,2017-09-26 00:33:52,2017-09-26 00:36:32,336313,002659252620170926092259,NaN,CT-20161118150202875,NaN,NaN
23310700,23310701,000000000002EF7F00000000000521B90000015EBB9AD8...,1970-01-01,video_open,2017-09-26 00:34:01,2017-09-26 00:36:32,336313,002659252620170926092259,NaN,CT-20160324155220625,TC,TMP4
17697716,17697717,000000000002EF7F00000000000521B90000015EBB9E2C...,1970-01-01,video_close,2017-09-26 00:37:39,2017-09-26 00:41:25,336313,002659252620170926092259,NaN,CT-20160324155220625,NaN,NaN
23400555,23400556,000000000002EF7F00000000000521B90000015EBB9EC8...,1970-01-01,video_open,2017-09-26 00:38:19,2017-09-26 00:41:30,336313,002659252620170926092259,NaN,CT-20170228161430676,TMG,TMP4
17245755,17245756,000000000002EF7F00000000000521B90000015EBB9FAB...,1970-01-01,video_close,2017-09-26 00:39:17,2017-09-26 00:41:34,336313,002659252620170926092259,NaN,CT-20170228161430676,NaN,NaN
23620207,23620208,000000000002EF7F00000000000521B90000015EBE3A62...,1970-01-01,video_open,2017-09-26 12:47:31,2017-09-26 12:52:13,336313,002659252620170926214717,BO-20170825093227112,CT-20170825093227112,TBI,MP4
17629524,17629525,000000000002EF7F00000000000521B90000015EBE3CEF...,1970-01-01,video_close,2017-09-26 12:50:18,2017-09-26 12:56:25,336313,002659252620170926214717,BO-20170825093227112,CT-20170825093227112,NaN,NaN
23622521,23622522,000000000002EF7F00000000000521B90000015EBE3D1D...,1970-01-01,video_open,2017-09-26 12:50:30,2017-09-26 12:56:31,336313,002659252620170926214717,NaN,CT-20160324155232897,TC,TMP4
17629807,17629808,000000000002EF7F00000000000521B90000015EBE3EE3...,1970-01-01,video_close,2017-09-26 12:52:26,2017-09-26 12:57:13,336313,002659252620170926214717,NaN,CT-20160324155232897,NaN,NaN
12550840,12550841,000000000002EF7F00000000000521B90000015EBE4085...,1970-01-01,book_open,2017-09-26 12:54:13,2017-09-26 12:57:45,336313,002659252620170926214717,BO-20150417014719992,CT-20150417014719992,TKI_09,EPUB
4848749,4848750,000000000002EF7F00000000000521B90000015EBE43C5...,1970-01-01,book_close,2017-09-26 12:57:46,2017-09-26 13:02:46,336313,002659252620170926214717,BO-20150417014719992,CT-20150417014719992,NaN,NaN
12325185,12325186,000000000002EF7F00000000000521B90000015EBE4641...,1970-01-01,book_open,2017-09-26 13:00:29,2017-09-26 13:06:31,336313,002659252620170926214717,BO-20170526160702902,CT-20170526160702902,LKWRD,PDFA
4849006,4849007,000000000002EF7F00000000000521B90000015EBE481E...,1970-01-01,book_close,2017-09-26 13:02:31,2017-09-26 13:06:57,336313,002659252620170926214717,BO-20170526160702902,CT-20170526160702902,NaN,NaN
12365911,12365912,000000000002EF7F00000000000521B90000015EBE4839...,1970-01-01,book_open,2017-09-26 13:02:38,2017-09-26 13:07:00,336313,002659252620170926214717,NaN,CT-20170829175007870,TBI,TEPUB
4863741,4863742,000000000002EF7F00000000000521B90000015EBE4908...,1970-01-01,book_close,2017-09-26 13:03:31,2017-09-26 13:07:11,336313,002659252620170926214717,NaN,CT-20170829175007870,NaN,NaN
12595947,12595948,000000000002EF7F00000000000521B90000015EBE4B6E...,1970-01-01,book_open,2017-09-26 13:06:08,2017-09-26 13:11:40,336313,002659252620170926214717,BO-20161026112937419,CT-20161026112937419,LKWRD,PDFA
8334151,8334152,000000000002EF7F00000000000521B90000015EBE4B6E...,1970-01-01,book_first_open,2017-09-26 13:06:08,2017-09-26 13:11:40,336313,002659252620170926214717,BO-20161026112937419,CT-20161026112937419,LKWRD,PDFA
6225966,6225967,000000000002EF7F00000000000521B90000015EBE5107...,1970-01-01,book_complete,2017-09-26 13:12:15,2017-09-26 13:16:55,336313,002659252620170926214717,BO-20161026112937419,CT-20161026112937419,NaN,NaN
4853027,4853028,000000000002EF7F00000000000521B90000015EBE5122...,1970-01-01,book_close,2017-09-26 13:12:22,2017-09-26 13:16:56,336313,002659252620170926214717,BO-20161026112937419,CT-20161026112937419,NaN,NaN
12326372,12326373,000000000002EF7F00000000000521B90000015EBE5365...,1970-01-01,book_open,2017-09-26 13:14:50,2017-09-26 13:17:33,336313,002659252620170926214717,BO-20161026112937446,CT-20161026112937446,LBNEW,PDFA
4853957,4853958,000000000002EF7F00000000000521B90000015EBE573D...,1970-01-01,book_close,2017-09-26 13:19:02,2017-09-26 13:22:18,336313,002659252620170926214717,BO-20161026112937446,CT-20161026112937446,NaN,NaN
12255092,12255093,000000000002EF7F00000000000521B90000015EBE5881...,1970-01-01,book_open,2017-09-26 13:20:25,2017-09-26 13:26:27,336313,002659252620170926214717,BO-20140726014815131,CT-20140726014815131,LN,PDFA
8522874,8522875,000000000002EF7F00000000000521B90000015EBE5881...,1970-01-01,book_first_open,2017-09-26 13:20:25,2017-09-26 13:26:27,336313,002659252620170926214717,BO-20140726014815131,CT-20140726014815131,LN,PDFA
6304006,6304007,000000000002EF7F00000000000521B90000015EBE5B87...,1970-01-01,book_complete,2017-09-26 13:23:43,2017-09-26 13:27:15,336313,002659252620170926214717,BO-20140726014815131,CT-20140726014815131,NaN,NaN
4656436,4656437,000000000002EF7F00000000000521B90000015EBE5C0F...,1970-01-01,book_close,2017-09-26 13:24:18,2017-09-26 13:27:26,336313,002659252620170926214717,BO-20140726014815131,CT-20140726014815131,NaN,NaN
12332821,12332822,000000000002EF7F00000000000521B90000015EBE5D38...,1970-01-01,book_open,2017-09-26 13:25:34,2017-09-26 13:31:34,336313,002659252620170926214717,BO-20140726020001611,NaN,LKWRD,PDFA
4823792,4823793,000000000002EF7F00000000000521B90000015EBE5EFD...,1970-01-01,book_close,2017-09-26 13:27:30,2017-09-26 13:31:55,336313,002659252620170926214717,BO-20140726020001611,NaN,NaN,NaN

In [4]:
df['event_name'].value_counts()

video_close         5401530
video_open          4163369
book_open           4041209
book_close          4004269
book_first_open     2246628
video_first_open    1483675
book_complete       1438758
audio_open           421802
audio_close          407875
audio_first_open      35346
Name: event_name, dtype: int64

In [31]:
len(df[df['book_code'] == 'BO-20170627173817922']['learner_id'].unique())

69873

In [20]:
#eliminate leaners with null id
df = df[df['learner_id'].notnull()]
df.shape

(23644461, 12)

In [21]:
#eliminate books with null code
df = df[df['book_code'].notnull()]
df.shape

(13507961, 12)

In [36]:
learner_book_df = df.groupby(['learner_id','book_code']).size().reset_index().rename(columns={0:'events_count'})

In [37]:
learner_book_df

         learner_id             book_code  events_count
0                 5  BO-20140726013700796             6
1                 5  BO-20140726014014719             3
2                12  BO-20140726013738070             3
3                12  BO-20140726014850882             2
4                12  BO-20140726014932178             3
5                12  BO-20140726015056775             3
6                12  BO-20140726020007169             3
7                12  BO-20140726020132287             3
8                12  BO-20140726020155449             3
9                12  BO-20150417014720005             3
10               12  BO-20150417014720158             2
11               12  BO-20150417044756103             3
12               12  BO-20160122145947170            64
13               12  BO-20160122145947197             2
14               12  BO-20161026170734904             4
15               12  BO-20170718174924596             2
16               12  BO-20170721152203601             4
17               12  BO-20170821132107257             2
18               12  BO-20170823174451695             4
19               12  BO-20170823174451702             4
20               12  CT-20160316150550038             2
21               12  CT-20160324103235064             4
22               12  CT-20160324155220625             4
23               12  CT-20160324155305682             4
24               12  CT-20160324155308223             1
25               12  CT-20170228104821045             4
26               12  CT-20170228104831284             4
27               12  CT-20170228104844193             4
28               12  CT-20170725163922724             8
29               12  CT-20170725163928449             4
...             ...                   ...           ...
5241632      666886  CT-20160324155305682             4
5241633      666886  CT-20160324155308223             6
5241634      666886  CT-20161118150202875             4
5241635      666886  CT-20170728144119680             8
5241636      666886  CT-20170829175003233            14
5241637      666888  BO-20140726015057279             1
5241638      666888  BO-20140726015521623             3
5241639      666888  BO-20150417014719940             2
5241640      666888  BO-20150417014719992             1
5241641      666888  BO-20170627173817926             2
5241642      666888  BO-20170821132107257             1
5241643      666888  CT-20160324155220625             2
5241644      666888  CT-20160324155232897             8
5241645      666888  CT-20160324155302588             4
5241646      666888  CT-20160324155305682             6
5241647      666888  CT-20160324155308223             6
5241648      666888  CT-20161118150202875             2
5241649      666888  CT-20170622155108547             2
5241650      666888  CT-20170725154830127             2
5241651      666888  CT-20170828112737628             2
5241652      666888  CT-20170829175003233             3
5241653      666893  BO-20140726014750459             3
5241654      666893  CT-20170728144716966             4
5241655      666897  BO-20170627173817926             2
5241656      666897  CT-20160324155305682             4
5241657      666897  CT-20160324155308223             4
5241658      666897  CT-20170829175003233             4
5241659      666897  CT-20170829175015315             4
5241660      666930  BO-20150417044757166             4
5241661      666930  BO-20150428174202912             3

[5241662 rows x 3 columns]

In [38]:
len(learner_book_df['learner_id'].unique())

264822

In [33]:
see = learner_book_df.groupby(['book_code']).agg({'learner_id': (lambda x: list(x.unique()))}).rename(columns={'learner_id':'learners'}).reset_index()
see

                  book_code                                           learners
0      BO-20140726013445290  [14130, 38953, 61192, 71254, 86943, 94170, 962...
1      BO-20140726013445793  [29659, 38953, 43082, 46496, 52716, 54040, 625...
2      BO-20140726013446298  [11236, 16515, 22594, 38953, 43082, 45452, 465...
3      BO-20140726013446802  [11236, 35097, 38953, 42501, 45452, 61517, 656...
4      BO-20140726013447306  [2480, 11021, 11588, 26723, 28225, 32024, 3468...
5      BO-20140726013447810  [34346, 38953, 55371, 81762, 95838, 124311, 12...
6      BO-20140726013448313  [22594, 27413, 38953, 45983, 46496, 48496, 540...
7      BO-20140726013448817  [38953, 47217, 81865, 100594, 104589, 119690, ...
8      BO-20140726013449321  [15657, 20552, 22079, 22098, 22594, 23874, 249...
9      BO-20140726013449824  [29806, 46496, 60964, 84796, 88849, 103013, 11...
10     BO-20140726013450328  [8153, 13486, 13693, 14130, 20154, 22594, 2428...
11     BO-20140726013450831  [468, 7473, 14130, 14250, 22594, 26845, 27143,...
12     BO-20140726013451335  [3105, 35097, 42531, 49877, 54969, 59760, 6756...
13     BO-20140726013451840  [72878, 79402, 106086, 130608, 135466, 165187,...
14     BO-20140726013452343  [43779, 69733, 70707, 102381, 107965, 124623, ...
15     BO-20140726013453351                           [273066, 332283, 584415]
16     BO-20140726013453854                   [149257, 293192, 314131, 388354]
17     BO-20140726013454358  [65075, 107060, 145851, 257629, 290334, 293871...
18     BO-20140726013454862  [19563, 20219, 84761, 129777, 288348, 451966, ...
19     BO-20140726013455365  [40813, 59141, 134309, 145695, 145851, 158974,...
20     BO-20140726013455869  [30230, 75843, 130179, 155945, 168754, 171865,...
21     BO-20140726013456373                                   [145851, 182392]
22     BO-20140726013456877  [7516, 41461, 43376, 64809, 64971, 68380, 7857...
23     BO-20140726013457380  [15258, 22557, 41589, 41675, 62646, 95860, 968...
24     BO-20140726013457884  [41589, 41675, 71768, 162387, 170530, 227305, ...
25     BO-20140726013458388           [162387, 227305, 314131, 581455, 584415]
26     BO-20140726013458891  [65749, 70744, 74361, 80210, 89747, 112369, 12...
27     BO-20140726013459395  [6805, 11126, 14828, 23316, 31462, 34017, 3560...
28     BO-20140726013459903  [106269, 112369, 127411, 478694, 510227, 51942...
29     BO-20140726013500406      [9709, 80210, 161070, 168336, 246198, 473138]
...                     ...                                                ...
11527  BO-20170823174440512                                            [26668]
11528  BO-20170823174451695  [12, 1592, 1611, 1926, 2224, 2460, 2677, 3161,...
11529  BO-20170823174451698  [529, 531, 1592, 1611, 1644, 1926, 2224, 2460,...
11530  BO-20170823174451702  [12, 1592, 1644, 1926, 2224, 2460, 2677, 2940,...
11531  BO-20170823174451706  [122190, 136423, 138163, 160627, 162795, 16804...
11532  BO-20170823174451711  [114041, 126865, 138163, 160627, 168042, 22221...
11533  BO-20170823174451716  [126865, 138163, 160627, 168042, 222216, 28550...
11534  BO-20170825093214563                                           [609646]
11535  BO-20170825093227112  [504, 752, 1297, 1961, 3618, 3886, 3996, 7460,...
11536  BO-20170825093227117  [297, 531, 549, 559, 603, 632, 752, 1109, 1145...
11537  BO-20170828132139162  [40681, 91746, 200217, 214729, 351837, 377969,...
11538  BO-20170828132139178  [8198, 11809, 40681, 64581, 94627, 94751, 1055...
11539  BO-20170829112328660                            [45119, 239836, 425947]
11540  BO-20170829112328664             [40430, 45119, 189949, 232330, 306803]
11541  BO-20170829112328667                                           [625495]
11542  BO-20170829112328669                                           [258627]
11543  BO-20170829112328672    [80078, 260168, 317668, 429276, 638847, 641644]
11544  BO-20170829112328674                                           [493682]
11545  BO-20170829112328676  [8316, 32180, 59848, 59852, 64283, 107626, 546...
11546  BO-20170829112328679                             [32180, 87701, 639013]
11547  BO-20170829112328684  [131558, 183374, 493778, 638289, 639181, 64051...
11548  BO-20170829112328687                   [149869, 150272, 251512, 293719]
11549  BO-20170829112328689                                     [40430, 64283]
11550  BO-20170829112328691                                     [32180, 87701]
11551  BO-20170829112328694                             [32180, 40430, 300972]
11552  BO-20170829112328697  [87701, 186360, 309956, 342225, 498444, 511282...
11553  BO-20170911134211349  [606681, 609636, 610740, 610745, 610839, 61547...
11554  BO-20170911134228336  [750, 752, 1851, 2289, 2319, 2564, 3300, 4078,...
11555  BO-20170911134245946                                           [616575]
11556  BO-20170925145257161                                           [610843]

[11557 rows x 2 columns]

In [36]:
len(list(see[see['book_code'] == 'BO-20170627173817922']['learners'].values)[0])

69873

In [24]:
books_stats = learner_book_df.groupby(['book_code']).agg({'learner_id': 'count'}).rename(columns={'learner_id':'no_of_learners'})
books_stats = books_stats.sort_values('no_of_learners', ascending=False).reset_index()
books_stats.to_csv('books_stats.csv')
books_stats

                  book_code  no_of_learners
0      BO-20170627173817922           69873
1      BO-20170724102316502           40267
2      BO-20170821132107208           38385
3      BO-20160329135654842           35846
4      BO-20170526154709672           33731
5      BO-20170124180543504           33583
6      BO-20170821132107257           32093
7      BO-20170825093227117           30817
8      BO-20140726015530182           28707
9      BO-20161226152837329           28146
10     BO-20170821132107285           27953
11     BO-20170821132107586           25502
12     BO-20170627173817926           24897
13     BO-20150420190236662           23094
14     BO-20150417044756134           22873
15     BO-20170821132107172           22871
16     BO-20140726020215086           22585
17     BO-20170724102316479           21610
18     BO-20170124130856024           21524
19     BO-20140726020100055           16506
20     BO-20140726015827440           15665
21     BO-20170821132106920           14744
22     BO-20170526154709682           13257
23     BO-20140726013728499           13102
24     BO-20170627173920980           13017
25     BO-20140726020132287           12513
26     BO-20141229105403512           12483
27     BO-20170821132106946           12006
28     BO-20170821132106923           11969
29     BO-20161026171155557           11871
...                     ...             ...
11527  BO-20150417044756810               1
11528  BO-20150417044756613               1
11529  BO-20150417045719344               1
11530  BO-20150417045719522               1
11531  BO-20150417045719528               1
11532  BO-20150417045719530               1
11533  BO-20150420190231429               1
11534  BO-20150420190231421               1
11535  BO-20150420190231400               1
11536  BO-20150420190231351               1
11537  BO-20150420190231242               1
11538  BO-20150420190231226               1
11539  BO-20150420190231183               1
11540  BO-20150420190231140               1
11541  BO-20150420190231120               1
11542  BO-20150420190231113               1
11543  BO-20150418135431321               1
11544  BO-20150418135431312               1
11545  BO-20150418135431306               1
11546  BO-20150418135431298               1
11547  BO-20150418135431263               1
11548  BO-20150418135431255               1
11549  BO-20150417050401316               1
11550  BO-20150417050401314               1
11551  BO-20150417050401303               1
11552  BO-20150417050401262               1
11553  BO-20150417050401069               1
11554  BO-20150417050401050               1
11555  BO-20150417050401044               1
11556  BO-20170925145257161               1

[11557 rows x 2 columns]

In [25]:
learner_stats = learner_book_df.groupby(['learner_id']).agg({'book_code': 'count'}).rename(columns={'book_code':'no_of_books'})
learner_stats = learner_stats.sort_values('no_of_books', ascending=False).reset_index()
learner_stats.to_csv('learner_stats.csv')
learner_stats

        learner_id  no_of_books
0           650868          424
1           288366          396
2           637531          371
3            80210          366
4           214103          365
5           524173          362
6           131379          361
7           614430          328
8           480005          326
9           242650          310
10          512130          309
11          576188          302
12          576095          297
13          520900          286
14          527204          283
15          576930          278
16          307912          276
17          576128          272
18          528142          272
19          433241          270
20          399570          269
21           67567          269
22          152496          268
23          234941          266
24          657265          263
25          573859          262
26          277305          262
27          418098          260
28           10147          260
29          400697          259
...            ...          ...
250710      410415            1
250711      223514            1
250712      577267            1
250713      223512            1
250714      223505            1
250715      223502            1
250716      223459            1
250717      223448            1
250718      410374            1
250719      410369            1
250720      223750            1
250721      223594            1
250722      223747            1
250723      410334            1
250724      410349            1
250725      410353            1
250726      223700            1
250727      223694            1
250728      223690            1
250729      223623            1
250730      577229            1
250731      577230            1
250732      577232            1
250733      223622            1
250734      223616            1
250735      223609            1
250736      223598            1
250737      577243            1
250738      223595            1
250739      483916            1

[250740 rows x 2 columns]

In [30]:
len(df[df['book_code'] == 'BO-20170627173817922']['learner_id'].unique())

69873

In [28]:
len(df[df['learner_id'] == 425983]['book_code'].unique())

82