In [1]:
library(data.table);
datadir <- '/home/webb/Compass_Recommender/';

content = readRDS(paste0(datadir,'content.rds'))
events = readRDS(paste0(datadir,'events.rds'))
learners = readRDS(paste0(datadir,'learners.rds'))

In [2]:
head(content)

  media_uri
1 https://www.youtube.com/watch?v=3PcmHSPVlKY&list=PLEGC1ZWh_UcM-K6sPxHjIlRt7OaqUkA6v&index=6
2 https://www.youtube.com/watch?v=TjmGTbNLj6Q&list=PLU4fxI_ACalZR4nKY105wsznalkf18no3&index=126
3 https://player.vimeo.com/external/182538809.sd.mp4?s=d9a2aefe38ac62aaf7d7c1171281854e8a1dba36&profile_id=165
4 https://www.youtube.com/watch?v=mEFASpHL9nM&list=PLEGC1ZWh_UcOanXzZ-9-VhItkOaIiJg7g&index=60&nohtml5=False
5 https://www.youtube.com/watch?v=QwmkfqKdFeo&index=70&list=PLEGC1ZWh_UcNl7zejuFXsVHaUhKCBpgMU
6 https://www.youtube.com/watch?v=FHFOO4s3DTk&index=138&list=PLEGC1ZWh_UcNl7zejuFXsVHaUhKCBpgMU
  category_seq content_seq
1 7                6
2 8            25834
3 7            22146
4 8            13713
5 7              305
6 7              373
  title                                                            duration
1 Santa, Where Are You?                                            150
2 10 Little Dinosaurs | Kids Songs | Super Simple Songs            133
3 Things in the Water | Rainbow Readers L3-40 | Compass Publishing 178
4 Polar Bears and How to Save Them | MISSION ANIMAL RESCUE         214
5 Swimming Song                                                    126
6 Hickory Dickory Dock                                             100
  category_name level_type age1 age2 level ⋯ src time transcript character
1 영어놀이      3~4        3    4     3    ⋯ alp NA   NA         NA
2 자연동물      3~6        3    5     1    ⋯ alp NA   NA         NA
3 영어놀이      8~9        7    8    11    ⋯ alp NA   NA         NA
4 자연동물      7~9        7    9    20    ⋯ alp NA   NA         NA
5 영어놀이      3~4        3    4     8    ⋯ alp NA   NA         NA
6 영어놀이      3~4        3    4     2    ⋯ alp NA   NA         NA
  advertistement category media_id playlist
1 NA             Alphabet     6    PLEGC1ZWh_UcM-K6sPxHjIlRt7OaqUkA6v
2 NA             Nature   13746    PLU4fxI_ACalZR4nKY105wsznalkf18no3
3 NA             Alphabet 12069    NA
4 NA             Nature    7103    PLEGC1ZWh_UcOanXzZ-9-VhItkOaIiJg7g
5 NA             Alphabet   303    PLEGC1ZWh_UcNl7zejuFXsVHaUhKCBpgMU
6 NA             Alphabet   369    PLEGC1ZWh_UcNl7zejuFXsVHaUhKCBpgMU
  plannel                paid
1 Super Simple Songs     FALSE
2 Super Simple Songs     FALSE
3 Compass Readers Level3  TRUE
4 MISSION ANIMAL RESCUE  FALSE
5 Little Baby Bum        FALSE
6 Little Baby Bum        FALSE

In [3]:
head(events)

  learner_id media_id src event_time          difficulty_rating like_rating
1 1347308    9132     alp 2018-04-27 23:57:34 3                 3
2 1347308    8491     alp 2018-04-27 23:55:29 2                 3
3 1026660      58     alp 2018-04-27 23:54:17 2                 3
4 1348168    8484     alp 2018-04-27 23:52:15 3                 2
5 1026660      17     alp 2018-04-27 23:50:47 2                 3
6 1347308    8484     alp 2018-04-27 23:50:10 2                 3

In [4]:
head(learners)

  learner_id provider_learner_id birthday   sex_real favorate1 favorate2
1 1008749    108786              2014-01-01 F        0         0
2  991439    102488              2008-01-01 F        0         0
3 1002444     96851              2013-01-01 M        0         0
4  991007     90383              2010-01-01 M        0         0
5 1662439     43925              2007-01-01 F        0         0
6  994237    104082              2017-01-01 F        0         0
  favorate3 level_by_word src
1 0          1            alp
2 0          1            alp
3 0         12            alp
4 0         17            alp
5 0         22            alp
6 0          4            alp

In [5]:
events = merge(events,content,by="media_id",all=F)
events = merge(events,learners,by="learner_id",all=F)

In [6]:
head(events)

  learner_id media_id src.x event_time          difficulty_rating like_rating
1 -140668     8918    hist  2018-04-10 22:48:19 2                 1
2 -140665        4    hist  2018-04-10 22:17:43 2                 1
3 -140665     8882    hist  2018-04-10 22:26:35 2                 1
4 -140665     8917    hist  2018-04-10 22:34:38 2                 1
5 -140615    11901    hist  2018-04-12 18:57:23 3                 3
6 -140541       59    hist  2018-04-10 16:06:51 2                 3
  media_uri
1 https://www.youtube.com/watch?v=ZM3xfWE3AQo&index=38&list=PLU4fxI_ACalYBdaDNyDe-QgoS0ECa7MIt
2 https://www.youtube.com/watch?v=UQfvAlmr5g0&list=PLEGC1ZWh_UcM-K6sPxHjIlRt7OaqUkA6v&index=4
3 https://www.youtube.com/watch?v=hRxf4bTS-_A&index=1&list=PLU4fxI_ACalYBdaDNyDe-QgoS0ECa7MIt
4 https://www.youtube.com/watch?v=rGX3wmVZiUA&index=37&list=PLU4fxI_ACalYBdaDNyDe-QgoS0ECa7MIt
5 http://player.vimeo.com/external/212540176.sd.mp4?s=eee97e1f6c890e536e24a0b99e78eb446d9f0db1&profile_id=165&oauth2_token_id=968817612
6 https://www.youtube.com/watch?v=efMHLkyb7ho&index=60&list=PLEGC1ZWh_UcM-K6sPxHjIlRt7OaqUkA6v
  category_seq content_seq
1 1            19288
2 7                4
3 1            19252
4 1            19287
5 4            27116
6 7               59
  title
1 DIY GLOW IN THE DARK SHELF Tutorial || NO power tools!
2 See You Later, Alligator
3 Toothless Night Fury Dragon Charm Polymer Clay Tutorial / Arcilla Polimerica
4 DIY MINIATURE BIRD WATERFALL ENVIRONMENT Resin & Polymer Clay Tutorial
5 Ponytail
6 One Potato, Two Potatoes
  ⋯ plannel            paid  provider_learner_id birthday   sex_real favorate1
1 ⋯ NerdECrafter       FALSE 140668              1959-01-01 M        2
2 ⋯ Super Simple Songs FALSE 140665              1999-01-01 M        2
3 ⋯ NerdECrafter       FALSE 140665              1999-01-01 M        2
4 ⋯ NerdECrafter       FALSE 140665              1999-01-01 M        2
5 ⋯ BADANAMU POP        TRUE 140615              2011-01-01 F        2
6 ⋯ Super Simple Songs FALSE 140541              2011-01-01 F        4
  favorate2 favorate3 level_by_word src
1 0         0         NA            hist
2 1         3         NA            hist
3 1         3         NA            hist
4 1         3         NA            hist
5 4         9         NA            hist
6 1         6         NA            hist

In [7]:
dim(events)

[1] 424659     53

In [8]:
write.csv(events, file = "/home/ravi/recommender_system/videos_recommender_ratings/preprocessed_data/events.csv")